### ISSUE TITLE
CI: Failures are prohibitively difficult to troubleshoot

### ISSUE THREAD

**Issue by mattbrictson** [vcr/vcr#1000]
The Cucumber and RSpec steps in CI redirect stderr to a temp file. This hides the output from the GitHub Actions console. As a result, when test execution fails (as recently happened in #995), it is impossible to see what is going wrong. Troubleshooting becomes a much more drawn out process.

E.g.

```
bundle exec rspec spec/ 2>> "${ALL_WARNINGS}"
```

The stderr capture is to facilitate the "check warnings" step, which fails the CI build if any tests output warnings. I assume this is to check for deprecations, so that these can be caught and corrected before impacting end users.

However, in the grand scheme, a deprecation warning is usually more of annoyance than a bug to end users. IMO avoiding these is not worth the trouble of complicating CI.

Perhaps a better way to guard against deprecations that are likely to eventually impact end-users is to add `ruby-head` to the build matrix. That way if a deprecation in a current version of Ruby is planned on becoming an error in a future version, it will fail the ruby-head build and maintainers will have a chance to correct it.

Alternatively, something like the [upload-artifact](https://github.com/actions/upload-artifact) action could be used to upload the captured stderr for troubleshooting purposes. This adds more complexity to the CI job, but if it works reliably, it could make troubleshooting possible while still maintaining the "check warnings" step.

**Comment by olleolleolle** [comment]
Thanks for writing up this! Absolutely on board with the trickiness - can we get the Upload Artifact going?

**Comment by mattbrictson** [comment]
> can we get the Upload Artifact going?

I tried setting it up in [this PR](https://github.com/vcr/vcr/pull/996), but I couldn't get it working. The upload seems to be skipped if the job fails. I think I can add `if: failure()` to ensure the upload happens on a failed job, but then it might not upload when the job succeeds. So I wasn't sure how to move forward. I was tempted just to remove `2>> "${ALL_WARNINGS}"` altogether, which is ultimately how I ended up finding the offending error message I was looking for.

I wonder if there is a best-practice for capturing deprecation warnings that we can learn from other projects, because I am feeling a bit like I am going against the grain of GitHub Actions trying to get it to work.

**Comment by mattbrictson** [comment]
It looks like there may have been something lost in the migration to GitHub Actions. If I am reading this bash syntax correctly, the stderr was saved to a file _and_ printed to the console (via `tee`). If we could restore that behavior, it would be a vast improvement to troubleshooting.

https://github.com/vcr/vcr/blob/5c0ded824dd8b1f9d50ab5d48a53be065b94ece8/script/ci.sh#L52
