### ISSUE TITLE
tests: Drop module HeaderDowncaser and use Hash#transform_keys instead

### ISSUE THREAD

**Issue by olleolleolle** [vcr/vcr#1012]
**Is your feature request related to a problem? Please describe.**

[Ruby 2.5 added `Hash#transform_keys`](https://www.bigbinary.com/blog/ruby-2-5-adds-hash-transform_keys-method)

**Describe the solution you'd like**

I'd like to omit the mixin in https://github.com/vcr/vcr/blob/20e6c2d3f6f6499725ec585053a0dd48f7d1b7f8/spec/support/http_library_adapters.rb#L1

**Describe alternatives you've considered**

Keeping the thing. Well, we don't support Ruby 2.4 any longer. No need.

**Comment by notapatch** [comment]
Hi [olleolleolle](https://github.com/olleolleolle) and all.

I've put a PR for the issue which you can, of course, review at your convenience(s)!
