### ISSUE TITLE
Calling `cassette.originally_recorded_at` in a `before_playback` hook causes an infinite loop

### ISSUE THREAD

**Issue by halorrr** [vcr/vcr#1013]
I was trying to add a hook to log a warning when a cassette is over 30 days old. I tried to do that with something like:

```Ruby
config.before_playback do |_interaction, cassette|
  recorded_at = cassette.originally_recorded_at

  if recorded_at.utc < (Time.now.utc - 30.days)
    puts "WARNING: #{cassette.name} is older than 30 days"
  end
end
```

As soon as `originally_recorded_at` is called on the cassette though, it loops back into the `before_playback` hook, and thus creates an infinite loop until it eventually throws a `SystemStackError`. It would appear that this date is not accessable without playing back the cassette? Is there a better way to hook into this data?

You can see the issue on my PR here https://github.com/halorrr/lunchmoney-ruby/pull/185

Ruby 3.3.0
Gem 6.2.0
HTTP Faraday 2.9.0 with net http
Mock webmock 3.19.1

**Comment by olleolleolle** [comment]
This line here invokes the hook very, very deliberately. Perhaps there is a way for you to dig at those internals and see if you can build a variant method/patch that would let you get at the data you want?

https://github.com/vcr/vcr/blob/20e6c2d3f6f6499725ec585053a0dd48f7d1b7f8/lib/vcr/cassette.rb#L216

**Comment by halorrr** [comment]
That helped, I was able to created a helper method as a workaround to extract that data using pretty much the same code that is in that file.

```Ruby
def extract_recorded_at_from_cassette(cassette)
  deserialized_hash = cassette.send(:deserialized_hash)["http_interactions"]

  wrapped_hash = deserialized_hash.map { |hash| VCR::HTTPInteraction.from_hash(hash) }.tap do |interactions|
    interactions.reject! do |interaction|
      interaction.request.uri.is_a?(String) && VCR.request_ignorer.ignore?(interaction.request)
    end
  end

  wrapped_hash.map(&:recorded_at).min
end
```
