### ISSUE TITLE
VCR doesn't combine well with existing Webmock stubs

### ISSUE THREAD

**Issue by mislav** [vcr/vcr#146]
I wanted to start using VCR in a project that already has a lot of manually set up Webmock stubs. Since replacing all the manual stubs with VCR-recorded HTTP interactions is a big undertaking, I wanted to make an incremental migration rather than doing it in one gigantic commit.

However, once VCR gets included in the test suite (via `hook_into :webmock`), it renders all existing Webmock stubs void. Consider this simple spec:

``` rb
describe "VCR and Webmock working together" do

  let(:url) { URI.parse 'http://example.com' }

  it "fails for net request" do
    expect { Net::HTTP.get(url) }.to raise_error
  end

  it "succeeds if the request is manually stubbed" do
    stub_request(:get, url.to_s).to_return(status: 200, body: 'hello')
    Net::HTTP.get(url).should eql('hello')
  end

end
```

Notice I didn't insert a cassette into VCR. I expected the real HTTP request to fail, since I don't want to allow external requests unless VCR is recording. But I also expected Webmock to return the stubbed request. Instead, VCR threw a VCR::Errors::UnhandledHTTPRequestError with a message "There is currently no cassette in use".

A workaround is that for the duration of a specific spec, VCR gets turned off:

``` rb
  before(:all) { VCR.turn_off! }
  after(:all) { VCR.turn_on! }
```

However I need to sprinkle all of this across my test suite to make old specs pass. It's not optimal.

I started looking into how VCR hooks into Webmock to see how can I patch this and enable incrementally migrating from Webmock stubs to VCR. However I wanted to ask first about was this intended.

**Comment by mkdynamic** [comment]
Re: the tip outlined in https://github.com/vcr/vcr/issues/146#issuecomment-4724462, thanks! We often use nested `VCR.use_cassette` blocks, so had to modify slightly to support that. Here's our modified version:

```ruby
VCR.instance_eval do
  turn_off!

  def use_cassette(*args, &blk)
    turn_on!

    return_val = super

    # support nested use_cassette blocks, only turn off on root block
    unless VCR.current_cassette
      turn_off!
    end

    return_val
  end
end
```

**Comment by mkdynamic** [comment]
Lol, disregard my comment. Totally unnecessary since https://github.com/vcr/vcr/commit/499646a2662905c51fc16aed54ef91493f9fcccd. I got a false negative when testing :)

**Comment by krainboltgreene** [comment]
No worries, I appreciate the comment either way.

On Wed, May 13, 2015 at 10:41 PM, Mark Dodwell <notifications@github.com>
wrote:

> Lol, disregard my comment. Totally unnecessary since 499646a
> <https://github.com/vcr/vcr/commit/499646a2662905c51fc16aed54ef91493f9fcccd>.
> I got a false negative when testing :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vcr/vcr/issues/146#issuecomment-101900104>.
>



-- 
Kurtis Rainbolt-Greene, Hacker
Software Developer
1631 8th St.
New Orleans, LA
70115

**Comment by jspillers** [comment]
I had a situation that required my test suite to accommodate VCR, WebMock only, and even some live http stuff all at the same time. Seeing as this is one of the few threads that comes up via google around this topic I figured I would leave a gist of my solution here in case anyone else has a similar problem they are trying to solve. https://gist.github.com/jspillers/a1eda91efb931b0eca7c

**Comment by krainboltgreene** [comment]
Much appreciated.

On Tue, Jun 9, 2015 at 4:13 PM, Jarrod Spillers <notifications@github.com>
wrote:

> I had a situation that required my test suite to accommodate VCR, WebMock
> only, and even some live http stuff all at the same time. Seeing as this is
> one of the few threads that comes up via google around this topic I figured
> I would leave a gist of my solution here in case anyone else has a similar
> problem they are trying to solve.
> https://gist.github.com/jspillers/a1eda91efb931b0eca7c
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vcr/vcr/issues/146#issuecomment-110505866>.
>



-- 
Kurtis Rainbolt-Greene, Hacker
Software Developer
1631 8th St.
New Orleans, LA
70115

**Comment by jakeonfire** [comment]
This worked for me to solve the OP's problem with newer APIs:
```ruby
RSpec.configure do |config|
  WebMock::API.prepend(Module.new do
    extend self
    # disable VCR when a WebMock stub is created
    # for clearer spec failure messaging
    def stub_request(*args)
      VCR.turn_off!
      super
    end
  end)

  config.before(:each) { VCR.turn_on! }
end
```

**Comment by bodrovis** [comment]
A minor thing to note. If you use `let` with VCR and pass it to Webmock, then it must be written as `let!` (otherwise you'll get an error saying VCR is disabled). For example:

```ruby
  let!(:season) do  # note the usage of let!
    VCR.use_cassette('seasons/season') do
      test_client.season 5
    end
  end
```

Then somewhere in your tests:

```ruby
    stub_request(:put, 'https://example.com/seasons/5').
      with(body: data).
      to_return(
        status: 200,
        body: JSON.dump(data.merge({id: season.id})),
        headers: {}
      )
```
