### ISSUE TITLE
Excon + Webmock issues

### ISSUE THREAD

**Issue by masterkain** [vcr/vcr#151]
Hi,
I'm using Excon in a custom library with few methods to interact with http to a node.js application.

The connection looks like this:

``` ruby
@@node_connection = Excon.new(Settings.app.node.uri, mock: Rails.env.test?)
```

and my spec like this:

``` ruby
it "should return true if Node.js returns 204" do
    Excon.stub({ method: :get }, { status: 204 })
    NodeApp.ping.should eq(true)
end
```

As you can see I enable mocking mode directly on the Excon connection and actively enable stubbing when I need it.
I then clean up stups with rspec:

``` ruby
config.after(:each) do
  Excon.stubs.clear
end
```

Now, this setup was serving me well, but I think the 2.x series broke it.
The first error is this:

```
     Failure/Error: NodeApp.ping.should eq(true)
     VCR::Errors::UnhandledHTTPRequestError:


       ================================================================================
       An HTTP request has been made that VCR does not know how to handle:
         GET http://0.0.0.0:3000/keepalive
```

If I disable VCR with `VCR.turn_off!` directly in the test, the error goes to webmock:

```
     Failure/Error: NodeApp.ping.should eq(true)
     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: GET http://0.0.0.0:3000/keepalive with headers {'Host'=>'0.0.0.0:3000'}

       You can stub this request with the following snippet:

       stub_request(:get, "http://0.0.0.0:3000/keepalive").
         with(:headers => {'Host'=>'0.0.0.0:3000'}).
         to_return(:status => 200, :body => "", :headers => {})
```

I did read the other ticket about a similar issue, but it's still possible to run with this kind of setup?

I'm not sure why Excon is really making the request when I disable VCR. I'm using Excon native mocking because I like the idea to have programmatically set the response header in the spec, which is what the small library is about, without really attempting the http call.

Thanks!

**Comment by repinel** [comment]
Hello, I think this is still an issue as the WebMock hook will mutate the headers even if the `excon` is not enabled. Just by having `Excon` defined.

https://github.com/vcr/vcr/blob/2b46c0243b262264e7db5d3a08937e4e0715d5f7/lib/vcr/library_hooks/webmock.rb#L62-L78
