### ISSUE TITLE
VCR Proxy Server

### ISSUE THREAD

**Issue by myronmarston** [vcr/vcr#187]
I've had the idea for a while to build a VCR proxy server, either as an extra gem that builds on top of VCR (e.g. `vcr-proxy`) or as an extra piece within the VCR gem itself.  There are a lot of different directions this could go, so I want to solicit feedback from VCR users before beginning any work on it.

For now, if you have any feedback on this, please add your thoughts at the bottom of this document.
## Problems the proxy server may solve
- As @jonleighton [has pointed out](https://twitter.com/jonleighton/status/227340874395295745), VCR relies pretty extensively on monkey patching to do its thing, at least if you use either FakeWeb or WebMock (as most people do). VCR can operate virtually monkey-patch free if you use it with Faraday, Excon or Typhoeus, as those libraries provide public APIs that VCR can use.  It'd be great to remove the dependency on monkey-patched code.
- VCR only works for ruby, and it only works for some HTTP libraries (although, at this point, it works for most ruby HTTP libraries). There have been [frequent](http://stackoverflow.com/questions/7802499/node-js-testing-with-vcr) [questions](http://stackoverflow.com/questions/7781881/java-alternative-for-rubys-vcr) asking about ports of VCR in other languages since it's such a useful tool for testing HTTP-dependent code.

I think a VCR proxy server is a promising potential way to solve both of these problems.  The proxy server could be used by any HTTP client, including those in other languages, and it wouldn't need any monkey patching at all.

Currently, VCR has some tooling that makes it possible to build your own proxy server (e.g. the VCR rack middleware), but that still takes a fair amount of work.  I'd like to make it trivial to use a VCR proxy server.
## Open Questions / Discussion
1. How should the proxy server know what cassette to use?  There are two basic ways we could do it here:
   1. **Internal** configuration -- when the proxy server receives a request it can select a cassette on the fly, based on some criteria or a callback or whatever.  This is similar to how you can use the [around_http_request hook](https://www.relishapp.com/myronmarston/vcr/v/2-2-4/docs/hooks/around-http-request-hook) to use a cassette for a particular HTTP request based on the HTTP request using a block callback.
   2. **External** configuration -- this is the typical way VCR is used: in your test suite, external from the HTTP request itself, you insert a cassette, and any HTTP requests that are made while the cassette is inserted use it.
2. What should the API to start the proxy server be?  Again, there's a couple possibilities here:
   1. **An executable** -- The gem could ship with an executable that starts the the proxy server. It would presumably accept options for things like what port to run on, as well as the path to a configuration file (which would probably be a simple be a ruby file).
   2. **A ruby class** -- Something like `VCR::ProxyServer.start(:port => 5000)`.
3. Should this be part of the VCR gem or a separate gem?
4. What HTTP server libraries should the proxy server use?  Just Rack/WeBrick? Thin? Something else?

I'm not sure which way the proxy server could work.  It seems to me that in the test suite of a ruby project, a developer would probably want to launch the proxy server in a separate thread, and control the cassettes it uses externally (similar to how VCR is used now). In the context of a non-ruby project, it would probably be more convenient to launch the proxy server in its own process using an executable, and pass the executable the path to a ruby file that configures cassettes based on a callback that receives the HTTP request as an argument.

Is one way more desirable than the other?  Or is there a way to meet both needs?  Are there other use cases I'm not thinking of here?

Please respond below with your thoughts!

**Comment by burgalon** [comment]
I've written a small sinatra_proxy which helps VCR too hook into a rack up.
https://gist.github.com/burgalon/e1e95c26f6e1bd762909

**Comment by mcfiredrill** [comment]
I think it would be great if VCR had a proxy like puffing-billy, or even if they could integrate together easier.
Getting VCR and puffing billy to work together is not super simple, and puffing billy's caching doesn't have all the features that VCR cassettes do.

**Comment by brutuscat** [comment]
Have you guys heard of [mountebank](http://www.mbtest.org/)

> mountebank is the first open source tool to provide cross-platform, multi-protocol test doubles over the wire. Simply point your application under test to mountebank instead of the real dependency, and test like you would with traditional stubs and mocks.

It seems that should be fairly "simple" to wire VCR here.

**Comment by krainboltgreene** [comment]
This is more relevant now that serverless exists.

**Comment by alexgenco** [comment]
This issue seems pretty stale, but FWIW we would very much like this feature, and the landscape for alternatives is surprisingly bare (we're using [wiremock standalone](http://wiremock.org/docs/running-standalone/), which is possibly deprecated, and is missing support for something like `record: :all` without weird hacks).

Are there any other vetted alternatives out there?

**Comment by dmitry** [comment]
@alexgenco what about puffing-billy, it's now mature. If you can setup proxy on your client, then it will work.

**Comment by ryanong** [comment]
puffing billy is a beast that already includes it's own request stubbing. It would probably be best to use `async-http` as a proxy and then use vcr to capture requests
