### ISSUE TITLE
VCR is not threadsafe

### ISSUE THREAD

**Issue by Fryguy** [vcr/vcr#200]
I've been having intermittent issues where VCR causes my tests to fail, raising UnhandledHTTPRequestError or causing deadlocks.

The code in question collects inventory from a third-party REST API, using rest-client.  Since we have to make about 30 API calls, we found that making each call in a separate thread gave us significant performance increases (~85% faster than unthreaded).

I recently started using VCR to add tests for this, and it seems the multi-threading is causing these errors.  Other tests that aren't multi-threaded do not exhibit these errors.

To narrow down and to prove it was the multi-threading, I added <code>allow_http_connections_when_no_cassette = false</code> and <code>allow_unused_http_interactions => false</code>, and was able to consistently get our test to fail with a different error.  Now, I get UnusedHTTPInteractionError, with a seemingly random set of unused interactions that change every time I run the spec.

The errors got me thinking that the bookkeeping around the VCR::Cassette::HTTPInteractionList may be involved.  For example, I added some puts instrumentation in VCR::Cassette#http_interactions, and I was able to show that on occasion, the right-side of the ||= statement was executed more than once.  I can also see that various methods in VCR::Cassette::HTTPInteractionList (like #response_for) do manipulations of that list.

I'm sure there are a bunch of places where synchronization needs to be added, but I haven't been able to narrow them all down.  The above are just some places I think might need it, but I'm not sure how to create a test for it.  I figured I'd open an issue to start discussing how to deal with this and to figure out how to make tests, as I am not sure even where to start.

**Comment by carhartl** [comment]
FWIW, - for the particular case of having vcr hook into webmock - I achieved vcr threadsafety for the case of making several http requests in threads within an application.

After synchronizing access to a cassette's http interactions the remaining pain point was the `VCR::LibraryHooks::WebMock.with_global_hook_disabled` method, e.g. the `global_hook_disabled` state on the module. Somehow synchronizing access to it didn't work, and so I temporarily changed `externally_stubbed?` to simply return false. For the time being that removed the ability to stub requests with webmock next to using a cassette (we don't use that feature at the moment).

Is it worth it to look further into it?

With the fork our tests now run reliably again, and no bogus recordings are being made.

**Comment by fotinakis** [comment]
FWIW, I was able to fix this for myself by using a mutex and synchronizing all HTTP threads handled by VCR:

```Ruby
require 'thread'

global_vcr_semaphore = Mutex.new

VCR.configure do |c|
  c.around_http_request do |request|
    global_vcr_semaphore.synchronize do
      request.proceed
    end
  end
end
```

This of course forces all HTTP requests to happen serially in tests, but might be a useable workaround.

**Comment by djberg96** [comment]
I thought https://github.com/vcr/vcr/pull/512 solved this.

However, @perlun says he is still seeing issues.

**Comment by perlun** [comment]
Yes, unfortunately so. Would you like a reproducible test case?

**Comment by djberg96** [comment]
@perlun Certainly.

**Comment by why-el** [comment]
Still seeing the issue as well. We spin a thread per http call, and we get sporadic `UnhandledHTTPRequestError` errors in the request specs that trigger this collection of calls.

**Comment by djberg96** [comment]
@perlun Do you have a reproducible test case for us?

**Comment by Daniel-ltw** [comment]
Not sure if this could be the solution. 

Could we use some iobuffer to write to the cassettes? 

I am assuming the read would be thread safe.

**Comment by DylanReile** [comment]
Running https://github.com/grosser/parallel_tests with our suite throws a host of VCR errors that aren't thrown when it's run single threaded.

**Comment by perlun** [comment]
@DylanReile Do you have a repo where it's being used, so we could investigate?

**Comment by saveriomiroddi** [comment]
Hello everybody!

I've just pulled a bit of my hair on this subject, so I can provide @perlun @djberg96 (and/or anybody who has some interest) a (very frequently) reproducible case.

The branch is: https://github.com/saveriomiroddi/geet/tree/reproducible_vcr_multithreading_case

Just clone the repo, switch the branch, `bundle install`, then:

    bundle exec rspec -e 'with labels, reviewers and milestones'

Around 80% of the times, the UT will fail, saying that one or more requests haven't been performed (i have VCR configured with `allow_unused_http_interactions: false`).

I've added for ease, in the HEAD commit, a printout of the requests. You can observe that all the intended requests are performed, eg.:

    >>> Sending request: GET https://api.github.com/repos/donaldduck/testrepo/milestones

You can see from the cassette (in this case, `create_pr.yml`) that there is only one instance of this sample request, so it's been surely sent, and replied to by VCR, but VCR loses track of it.

Here's an error with stack trace:

    VCR::Errors::UnusedHTTPInteractionError:
      There are unused HTTP interactions left in the cassette:
        - [get https://api.github.com/repos/donaldduck/testrepo/milestones ""] => [200 "[{\"url\":\"https://api.github.com/repos/donaldduck/testrepo/milestones/1\",\"html_ur"]
    # /path/to/gems/vcr-3.0.3/lib/vcr/cassette/http_interaction_list.rb:68:in `assert_no_unused_interactions!'
    # /path/to/gems/vcr-3.0.3/lib/vcr/cassette.rb:68:in `eject'
    # /path/to/gems/vcr-3.0.3/lib/vcr.rb:156:in `eject_cassette'
    # /path/to/gems/vcr-3.0.3/lib/vcr.rb:191:in `use_cassette'
    # ./spec/integration/create_pr_spec.rb:32:in `block (3 levels) in <top (required)>'

Let me know if you need further help, although the case is fairly simple.

**Comment by saveriomiroddi** [comment]
To be very clear, the error I'm experiencing is that VCR loses track of what it replied to, so, while the replies are correct, the configuration `allow_unused_http_interactions: false` will cause an error to be triggered.

**Comment by saveriomiroddi** [comment]
On my project, the PR I've submitted fixes the `UnhandledHTTPRequestError` issue; there is some reasonable expectation that this would fix this specific problem also for @Fryguy.

About the deadlocking though, definitely not :scream:. I would gladly try to debug it, but on my project I don't have deadlocking problems, therefore, I can't reproduce it.

**Comment by saveriomiroddi** [comment]
@DylanReile Hey Dylan, do you have ready the list of steps required to setup the parallel gem on this project? I'd like to have a review of the critical sections, and this will save me a tiny bit of time. Otherwise, no problem, I'll check it out.

**Comment by blj** [comment]
We have been facing similar issues in CI, but not locally and concluded that VCR gem is not threadsafe. Then we reaslied the outgoing API calls were made to a slightly different URL because the gem making the URL also puts access key as query string which was different in CI.

So first make sure that the URL matches in the cassette, it could be just that.

**Comment by krainboltgreene** [comment]
Yeah it's hard to figure out where the true problem lies with a VCR enabled
systems because you're dealing with so many complexities.

**Comment by andreynering** [comment]
I had success preventing intermittent errors on CI by monkey-patching the library like this:

```ruby
module VCR
  UseCassetteMutex = Mutex.new
      
  alias original_use_cassette use_cassette

  def use_cassette(*args, &block)
    VCR::UseCassetteMutex.synchronize do
      original_use_cassette(*args, &block)
    end
  end
end
```
