### ISSUE TITLE
How to reliably filter basic_auth credentials out of the URI?

### ISSUE THREAD

**Issue by nathany** [vcr/vcr#201]
Hi,

I added the following code to filter out my basic auth credentials, which works on the first request (the replacement is made) but on subsequent requests I get the `VCR::Errors::UnhandledHTTPRequestError:` error with a URI that includes a real username/password.

``` ruby
c.filter_sensitive_data('__user:pass__') { |interaction| 
    interaction.request.uri[/https?:\/\/(.+)@/,1] }
```

I'm using Ruby 1.9.3-p286 and hooked into webmock, tested with both VCR 2.2.5 and master. I also tried fakeweb on VCR 2.2.5, which does the same thing.  I'm just using Ruby's built in Net::HTTP for the calling code and not doing anything with webmock/fakeweb. VCR is configured via RSpec metadata as per RailsCast Pro #291.

**Comment by jroes** [comment]
I support the API suggested by @davout here

**Comment by stevenharman** [comment]
With the recent changes to Webmock 2.0, specifically, [not matching basic auth credentials in the `userinfo` part of the URL](https://github.com/bblimke/webmock/blob/master/CHANGELOG.md#200), I suddenly find my self in want of this feature. After upgrading to Webmock 2.0 an re-recording our cassettes, we're no longer filtering the basic auth credentials b/c Webmock is now, correctly, putting them in the `Authorization` header.

**Comment by mcfiredrill** [comment]
@stevenharman Apologies if I'm missing something obvious, but is it possible to achieve this with `filter_sensitive_data`?

**Comment by stevenharman** [comment]
Yes, totally. In fact, that's what we're currently doing.

```ruby
VCR.configure do |c|
  # ... other configuration stuff

    c.filter_sensitive_data('<ENCODED AUTH HEADER>') { Base64.encode64("#{ENV.fetch('SECRET_USER_NAME')}:#{ENV.fetch('SPECIAL_USER_PASS')}").chomp }

end
```

**Comment by mcfiredrill** [comment]
@stevenharman I see what you are saying. 😟 

 I wonder if this is not possible with any existing VCR functionality.

**Comment by subelsky** [comment]
@stevenharman you might want to use `Base64.strict_encode64` which removes the need for newline and as a bonus does not add its own newline every 60 characters (which may bite you if you start using longer basic auth values)

**Comment by subelsky** [comment]
Here's how I'm solving this issue, could be generalized to something more widely useful. @stevenharman note that it doesn't require as much foreknowledge of the basic auth string. Probably don't even need the domain name in there! Just `@`:

```ruby
match_basic_auth_in_uri = %r|https://(?<basic_auth_str>.+)(?=@api.example.com/)|

VCR.configure do |c|
  c.filter_sensitive_data("BASIC_AUTH_STR") do |interaction|
    interaction.request.uri[match_basic_auth_in_uri,:basic_auth_str]
  end
end
```
```

**Comment by subelsky** [comment]
I spoke too soon. Doing it that way does persist a file without the basic auth secret but also prevents the tape from playing back correctly. Back to the drawing board.

**Comment by ianks** [comment]
This is a huge pain point for me. Filtering is easy, but configuring a matcher is a PITA for headers. Something like `uri_with_params` would be awesome for headers: `request_without_headers`

**Comment by AlexanderRD** [comment]
Where's the upvote button on @davout 's comment? :)

**Comment by cilim** [comment]
Thank you gem maintainers for you efforts ❤️ 

I'm picking up this discussion 5 years later, cause I really need this feature.

My 1st attempt:
```ruby
VCR.configure do |c|
  c.cassette_library_dir = "#{Rails.root}/spec/vcr_cassettes"
  c.hook_into :webmock

  c.filter_sensitive_data('username:password') do |interaction|
    next unless interaction.request.uri.include?('a.really.bad.api.com')
    
    interaction.request.uri.scan(/^https?:\/\/(.*)@a.really.bad.api.com/).first.first
  end
end
```

Doesn't work the 2nd time around when playing it back.

Then I tried this:
```ruby
  c.before_record do |interaction|
    next unless interaction.request.uri.include?('a.really.bad.api.com')
    
    safe_uri = interaction.request.uri.gsub(
      "#{Rails.application.secrets.bad_api_username}:#{Rails.application.secrets.bad_api_password}",
      "username:password"
    )
    
    interaction.request.uri = safe_uri
  end
  
  c.before_playback do |interaction|
    next unless interaction.request.uri.include?('a.really.bad.api.com')
    
    unsafe_uri = interaction.request.uri.gsub(
      /username:password/,
      "#{Rails.application.secrets.bad_api_username}:#{Rails.application.secrets.bad_api_password}"
    )
    
    interaction.request.uri = unsafe_uri
  end
```

Same thing...it wants to send the proper request, but the recorded cassette has `username:password` in it, so VCR raises the well-known error:
```
An HTTP request has been made that VCR does not know how to handle
```

Are there any plans for this, or should I just stub the request and give up on VCR for this particular case?

**Comment by olleolleolle** [comment]
@cilim Maaaaybe you can create a discussion on this, linking to this Issue, in order to get more eyes on it. (Very few people are following _everything_ that happens.)

**Comment by cilim** [comment]
Sure @olleolleolle, just let me know where to create a discussion on this? In the form of a new issue perhaps or? 😄

**Comment by olleolleolle** [comment]
@cilim Aha, GitHub now features a new Discussion tab, which you can navigate to in this repo. There, a threaded discussion forum exists!

**Comment by isaacbowen** [comment]
The resulting discussion, if anyone else passes through here looking for it: https://github.com/vcr/vcr/discussions/887 ☺️
