### ISSUE TITLE
Feature: Coexist with FakeFS in a Rspec suite

### ISSUE THREAD

**Issue by taqtiqa-mark** [vcr/vcr#234]
It would be convenient to run a VCR example within the scope of FakeFS. 

Running something like.
`FakeFS::FileSystem.clone('/path/bdd/cassettes', '/path/bdd/cassettes')` in a `before(:each|:all){}` block _should_ make existing cassettes visible to VCR. I do this cloning with some file fixtures to replicate the phase after the download code has run. 

Under FakeFS a `Dir.glob` is truncated and this might be confusing VCR? 

```
puts Dir.glob('/path/bdd/cassettes/**/*')
bdd/cassettes
```

It seems that getting updated cassettes back out from under FakeFS is within the scope of VCR. Right now I can get some VCR specs to pass, but am having trouble getting the cassettes to work, then there is the issue of the transfer out of FakeFS.

Does this sound reasonable feature request?

**Comment by tylercollier** [comment]
For anyone else interested, I ended up creating a gem as Myron suggested. I called it [vcr-fakefs](https://github.com/tylercollier/vcr-fakefs).
