### ISSUE TITLE
NTLM authenticaton is not working with webmock

### ISSUE THREAD

**Issue by RmMsr** [vcr/vcr#297]
I am trying to use VCR to test against Microsoft Exchange Web Services (EWS). Which is an SOAP Service running on IIS via SSL. Authentication is done using [NTLM](http://en.wikipedia.org/wiki/NTLM). The EWS protocol is handled by the nicely [Viewpoint gem](https://github.com/zenchild/Viewpoint) which uses **HTTPClient** internally.

Without mocking, the connection works fine. As soon as the webmock hook ist configured for VCR the NTML negotiation fails. I am not familiar with NTLM. It looks like the correct headers are send out but the server just answers with `HTTP/1.1 401 Unauthorized`.

I prepared this testfile:

``` ruby
require 'httpclient'
require 'vcr'

@url = 'https://example.com/ews/services.wsdl'
@username = 'user'
@password = 'password'
@debug = false

def get_with_ntlm_and_ssl(debug = @debug)
  http = HTTPClient.new
  http.ssl_config.verify_mode = OpenSSL::SSL::VERIFY_NONE
  http.debug_dev = STDOUT if debug
  http.set_auth @url, @username, @password
  puts http.get(@url).status
end

# Works before mocking
get_with_ntlm_and_ssl

VCR.configure do |config|
  config.cassette_library_dir = 'test_vcr'
  config.hook_into :webmock
  config.debug_logger = STDERR if @debug
  config.allow_http_connections_when_no_cassette = true
end

# Authentication fails
get_with_ntlm_and_ssl

VCR.use_cassette('ntlm_ssl', :record => :all, :match_requests_on => [:host, :uri, :headers]) do
  # No recordings are made
  get_with_ntlm_and_ssl
end
```

You will probably need a Microsoft IIS Server to verify the issue. I hope I can disable SSL to see if it makes a difference.

**Comment by richkettle** [comment]
I am getting this error. All these years later. @RmMsr I know its been 3 years but did you find a solution?
