### ISSUE TITLE
Spike towards better thread safety

### ISSUE THREAD

**Issue by fwoeck** [vcr/vcr#403]
Hi, this commit contains my take on the thread-safety issues #200, #285, #376 
https://github.com/fwoeck/vcr/commit/06f0f25a743e665f4b8b4197e63cc579a92c1f04

I primarily added some mutexes, made cassette names thread-local and improved the web mock after-hook detection for around-hooks. If you find it worthwhile, I'd clean it up, add some specs and make a pull request out of it.

For testing I used my current project (rbx 2.2.6 with concurrently running specs and requests - using webmock/net-http and around-hooks). The likelihood of seeing errors as described in the aforementioned issues was about 100%:
- VCR::Errors::UnhandledHTTPRequestError 
- undefined method `resume' for nil:NilClass
- There is already a cassette with the same name

My first try was to make cassettes global and synchronized but I think there lies a contradiction with the around_http_request-hooks. When they are used in a threaded environment, I didn't find a way to avoid naming conflicts and other failure.

So cassettes are thread-local now, with global persistence. This actually means, that the example, @lucassus gave in issue #200 won't work, but it works like this:

```
require "vcr"
require "excon"

VCR.configure do |c|
  c.cassette_library_dir = './tmp'
  c.hook_into :excon
  c.default_cassette_options = {record: :once}
end

queries = 200.times.map { |n| "query-#{n}" }
threads = []

queries.each_slice(5) do |sliced_queries|
  slice = threads.size
  threads << Thread.new do
    VCR.use_cassette("google_search_#{slice}") do
      sliced_queries.each do |q|
        Excon.get("http://google.com/?q=#{q}")
      end
    end
  end
end

threads.map(&:join)
```

Also, when using around-hooks, webmock's after-request error can be avoided, because it actually calls the after-hook twice. This was causing the fibers to fail with "undefined method ... on nil".

##### What the patch does
- it runs the current specs with mri 2.1 and rbx 2.2.6 and runs the features with mri
- I couldn't see any of the errors mentioned before in my tests
- I didn't see any deadlocking

##### What it doesn't do
- it has some timing issues with the cucumber features with rbx - although that's actually the case for the current vcr master branch, too
- it doesn't synchronize configuration and persistence - they remain global for now. Is it ok this way?

##### What needs to be done
- adding some specs for the test cases described above
- testing against the other supported platforms

**Comment by krainboltgreene** [comment]
Looks like this wasn't ever finished/solved, but it does seem to have opened up the idea of chucking `around_http_request`.

**Comment by djberg96** [comment]
@fwoeck Any progress on this?

**Comment by mrbrdo** [comment]
:+1: It would be nice to be finally able to use vcr with threaded apps, I have (had) several such cases...

**Comment by djberg96** [comment]
http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/433878

**Comment by jasonfb** [comment]
wait helpers seem to be the only answer here; I wrote an extensive blog post (that doesn't actually discuss VCR but concepts can be applied) https://medium.com/@jaflebol/capybara-taming-the-hydrochoerus-8fcd28d70787

I am also looking for more wait-helper strategies. I have taken wait helpers so far that now I actually code my code into such a way to be friendly to wait helpers

**Comment by ishan123456789** [comment]
Hi I'm still facing issue with VCR not working as expected when using with parallel_tests, any fix for it?
