### ISSUE TITLE
remove patron as it is unmaintained and buggy

### ISSUE THREAD

**Issue by pravi** [vcr/vcr#447]
see https://github.com/bblimke/webmock/issues/391

spec/monkey_patches.rb require patron.

**Comment by krainboltgreene** [comment]
I also wouldn't mind having repositories specifically for testing vcr with various HTTP libraries.

**Comment by pravi** [comment]
anyway they seem to be active again https://github.com/toland/patron/issues/72#issuecomment-216322122
