### ISSUE TITLE
VCR Specification

### ISSUE THREAD

**Issue by krainboltgreene** [vcr/vcr#465]
There are enough VCR-likes out there that we should probably consider a specification for how they operate. Even if it's just a few rules on persistence and interaction.

There are two sides to VCR:
1. Mocking HTTP requests
2. Caching HTTP requests

The first will need a specification on how it operates, and the second needs a specification on storage format. There is an initial attempt [here](https://www.relishapp.com/vcr/vcr/docs/cassettes/cassette-format) to define the cassette format.

**Comment by sigmavirus24** [comment]
Isn't 2 taken care of already? I thought VCR 2.0 published the cassette format as a specification 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by krainboltgreene** [comment]
Got a link? I can't find anything in Google.

**Comment by krainboltgreene** [comment]
Used "format" instead of "specification", got https://www.relishapp.com/vcr/vcr/docs/cassettes/cassette-format

**Comment by sigmavirus24** [comment]
Yep that's it. That's what I used when building Betamax.

**Comment by markng** [comment]
What intent do we have to standardise things? I like the idea that we could standardise the tape storage mechanism, with the intent that you could use recorded tapes from one with another. I wonder if standardising the interface might lose you the advantage of providing idiomatic interfaces, on the other hand.

**Comment by sigmavirus24** [comment]
@markng there are a lot of "ports" to other languages currently. As far as I know [betamax](/sigmavirus24/betamax) is the first to be able to use cassettes from VCR (assuming they're stored in JSON for reasons I won't complain about here ;)) and it also keeps the closest to VCR's API (although as I mentioned, the global configuration aspect is grating on my nerves). Having a bunch of proofs of concept of VCR's API in other languages is probably a good idea to have before writing a specification. We should figure out what the most reasonable common subset of features is to have.

**Comment by krainboltgreene** [comment]
Yeah, I'm not really keen on the global configuration practice.

Sharing cassettes is the most obvious benefit to standardization, but also because there are a lot of languages out there that do web dev. If we can save even one person a lot of time by laying out how a VCR-like works we win.

**Comment by adri** [comment]
Is this really worth it? I mean a VCR implementation records the requests of a system under test. Why would there be a need to share those with other implementations? Unless the system under test is implemented in different languages issuing the exact same requests I wouldn't see a benefit. 

(I'm maintaining [php-vcr](https://github.com/php-vcr/php-vcr)).

**Comment by krainboltgreene** [comment]
It was not really worth it.
