### ISSUE TITLE
Support for Thrift?

### ISSUE THREAD

**Issue by jrom** [vcr/vcr#469]
Tried using VCR for specing https://github.com/evernote/evernote-oauth-ruby integration and recording the API responses (Thrift) but as soon as the spec is using the recording, it shows an error:

```
     Thrift::ProtocolException:
       Missing version identifier
```

Any idea on how to add support for Thrift? Didn't dig deep but there's definitely something that VCR is not recording/replaying properly.

Thanks!

**Comment by jrom** [comment]
Hm, interesting, changed from `:fakeweb` to `:faraday` and now seems to be working. Will do some more research but i'll leave this here FWIW.

**Comment by krainboltgreene** [comment]
We're going to be dropping support for Fakeweb in 3.0.0, I believe. So try
to use webmock or faraday.

**Comment by jrom** [comment]
Hey @krainboltgreene thanks for replying! I deleted that comment after realizing that it just worked because VCR was just always bypassing the recording and going straight to Evernote's API. So issue remains the same, probably due to some sort of binary encoding/decoding that Thrift gets messed up with. Doing some research on it.

**Comment by jrom** [comment]
Fixed by adding:

```
  c.preserve_exact_body_bytes do |http_message|
    http_message.body.encoding.name == 'ASCII-8BIT' ||
    !http_message.body.valid_encoding?
  end
```

**Comment by fornellas** [comment]
@jrom this might be related to your issue: https://bugs.ruby-lang.org/issues/2567#note-35.
