### ISSUE TITLE
Thinking about writing a MessagePack persistence option

### ISSUE THREAD

**Issue by dogweather** [vcr/vcr#472]
Would anyone else like to have this? [MessagePack](http://msgpack.org/) is semantically just like json, but much smaller and faster. For me, the use case is smaller cassette files, which would make it feasible to check them in to git/github.

**Comment by krainboltgreene** [comment]
I believe there's a persistence engine layer built into VCR. If you make the gem (vcr-message_pack or something) I would add it to the org.

**Comment by sigmavirus24** [comment]
I would expect anything kept in the org to be essentially endorsed as high quality by the organization owners/VCR authors. Perhaps it's best to let this remain as @dogweather's 3rd party gem to determine popularity and reliability?

**Comment by myronmarston** [comment]
> I believe there's a persistence engine layer built into VCR.

There is indeed.  It sounds like @dogweather intends to use MessagePack for serialization, which is orthogonal to persistence.  You can use any serializer (e.g. YAML, JSON, MessagePack, XML) with any persistence engine (file system, S3, redis, riak, etc).  I'd expect MessagePack to be an alternate serializer.

**Comment by dogweather** [comment]
Thanks for the pointers: I'll look into that route.

**Comment by krainboltgreene** [comment]
Sorry, yes I meant serialization engine layer.

**Comment by krainboltgreene** [comment]
@dogweather Let me know when you've got the repository up, I'll fork it to the vcr org after I give it a look.
