### ISSUE TITLE
Support for http.rb?

### ISSUE THREAD

**Issue by zuk** [vcr/vcr#477]
Has anyone been able to get VCR to work with the (rather tragically named) [http.rb gem](https://github.com/httprb/http.rb)?

The official Twitter gem has recently switched from Faraday to http.rb, so I suspect there are or will be a number of people looking for VCR support for this library.

**Comment by zuk** [comment]
Looks like it works with WebMock, but I had to change the serializer to `:json`. I was getting errors like the following when trying to use the defaul `:yaml`/`:psych` serializer with http.rb and webmock:

`yaml_tree.rb:70:in `block in initialize': undefined method `name' for nil:NilClass (NoMethodError)`

**Comment by krainboltgreene** [comment]
Hm, okay. I'll look into it. Surprised they switched away from Faraday.

**Comment by pxlpnk** [comment]
@zuk I ran into the same problem with the psych yaml serializer on `ruby 2.1.2p95`
* http (v0.7.1)
* vcr (2.9.3)
* webmock (1.20.4)

It seems like the hash that is passed in [here](https://github.com/vcr/vcr/blob/master/lib/vcr/cassette/serializers/yaml.rb#L33) is somehow invalid for psych.
What I don't understand is that the hashes in both versions are (except timestamps and variable data) identical. Any idea where to look further?

**Comment by zuk** [comment]
Like I said, switching to `:json` as the serializer did the trick for me. Everything's been working great since.

**Comment by pxlpnk** [comment]
I would prefer to resolve the issue and not have to re-record all my requests. Or is there a way to transform them?

**Comment by cupakromer** [comment]
Faraday does not support streaming. If Twitter is allowing file transfers, they would need to use something else for that part of the code. Additionally, faraday is becoming a defunkt project (lostisland/faraday#454) and being replaced by https://github.com/lostisland/hurley

**Comment by krainboltgreene** [comment]
hurley looks interesting. I'll have to work on a feature branch to integrate it.

**Comment by pxlpnk** [comment]
@zuk FYI this seems to be resolved with http.rb 0.8.0

**Comment by vcavallo** [comment]
I came here for the same reason as the OP - trying to use VCR with http.rb. Are there plans to support this without using webmock?

**Comment by Saoibman** [comment]
Done

**Comment by Saoibman** [comment]
Done po

**Comment by Saoibman** [comment]
Iphone 14
