### ISSUE TITLE
Improve the debug message of VCR

### ISSUE THREAD

**Issue by dnesteryuk** [vcr/vcr#478]
When there isn't a cassette to handle a request, VCR returns an error like:

```
An HTTP request has been made that VCR does not know how to handle:
  GET http://google.com/client/api?listAll=true&page=2&pagesize=20&response=json
  Body: 

VCR is currently using the following cassette:
  - /home/dnesteryuk/project/cars.yml
  - :record => :none
  - :match_requests_on => [:method, #<struct VCR::RequestMatcherRegistry::URIWithoutParamsMatcher params_to_ignore=["_", "sessionkey"]>, :body]

Under the current configuration VCR can not find a suitable HTTP interaction
to replay and is prevented from recording new requests. There are a few ways
you can deal with this:

  * If you're surprised VCR is raising this error
    and want insight about how VCR attempted to handle the request,
    you can use the debug_logger configuration option to log more details [1].
  * You can use the :new_episodes record mode to allow VCR to
    record this new request to the existing cassette [2].
  * If you want VCR to ignore this request (and others like it), you can
    set an `ignore_request` callback [3].
  * The current record mode (:none) does not allow requests to be recorded. You
    can temporarily change the record mode to :once, delete the cassette file 
    and re-run your tests to allow the cassette to be recorded with this request [4].
```

When a lot of cassettes are applied:

```ruby
  VCR.use_cassette('cars') do
    VCR.use_cassette('cars2') do
      VCR.use_cassette('cars3') do
        VCR.use_cassette('cars4') do
          # do HTTP call here
        end
      end
    end
  end
```

This message doesn't help too much. I was thinking to improve that message with all lists of aplied cassettes:

```
An HTTP request has been made that VCR does not know how to handle:
  GET http://google.com/client/api?listAll=true&page=2&pagesize=20&response=json
  Body: 

VCR is currently using the following cassettes:
  - /home/dnesteryuk/project/cars.yml
  - /home/dnesteryuk/project/cars2.yml
  - /home/dnesteryuk/project/cars3.yml
  - /home/dnesteryuk/project/cars4.yml

Under the current configuration VCR can not find a suitable HTTP interaction
to replay and is prevented from recording new requests. There are a few ways
you can deal with this:

  * If you're surprised VCR is raising this error
    and want insight about how VCR attempted to handle the request,
    you can use the debug_logger configuration option to log more details [1].
  * You can use the :new_episodes record mode to allow VCR to
    record this new request to the existing cassette [2].
  * If you want VCR to ignore this request (and others like it), you can
    set an `ignore_request` callback [3].
  * The current record mode (:none) does not allow requests to be recorded. You
    can temporarily change the record mode to :once, delete the cassette file 
    and re-run your tests to allow the cassette to be recorded with this request [4].
```

Let me know your opinion, I can do pull request for this change.

**Comment by krainboltgreene** [comment]
That's a pretty damn good idea. I'll merge it if it gets PRd.

**Comment by sigmavirus24** [comment]
I would rather the record mode and matchers not be removed from the exception message. The mode is helpful and while your example of a matcher that isn't easily representable is valid, I think there should maybe be a better way of handling those.

**Comment by dnesteryuk** [comment]
I created code to show the full list of used cassettes https://github.com/dnesteryuk/vcr/commit/b261b7a207ce0d7f4f1398371df4e32b04f679a8, but there are a few questions to maintainers of the project.

1. [There](https://github.com/dnesteryuk/vcr/blob/b261b7a207ce0d7f4f1398371df4e32b04f679a8/lib/vcr/errors.rb#L86-L96) to get all cassettes I eject them from the VCR. I guess it should not be a problem since when we display an error, the test is already failed and we don't need cassettes to be in the stack anymore. But, I am not sure.
2. I added some new tests like [this one](https://github.com/dnesteryuk/vcr/blob/better_debug/spec/lib/vcr/errors_spec.rb#L113-L119). But, there may be more cases which I need to test. Most of written tests are about one cassette in the stack. Should I add additional tests to verify similar cases, but for the situation when we have a few cassettes? Actually, the current code doesn't care how much cassettes in the stack we have, therefore, I guess the current test suit is ok.

Please, provide your feedback. If the changes are ok, I will create a pull request. Thank you.

**Comment by krainboltgreene** [comment]
I think a pull request for this would be great, we can review it in there!

On Thu, Aug 13, 2015 at 6:58 AM, Dmitriy Nesteryuk <notifications@github.com
> wrote:

> I created code to show the full list of used cassettes dnesteryuk@b261b7a
> <https://github.com/dnesteryuk/vcr/commit/b261b7a207ce0d7f4f1398371df4e32b04f679a8>,
> but there are a few questions to maintainers of the project.
>
>    1. There
>    <https://github.com/dnesteryuk/vcr/blob/b261b7a207ce0d7f4f1398371df4e32b04f679a8/lib/vcr/errors.rb#L86-L96>
>    to get all cassettes I eject them from the VCR. I guess it should not be a
>    problem since when we display an error, the test is already failed and we
>    don't need cassettes to be in the stack anymore. But, I am not sure.
>    2. I added some new tests like this one
>    <https://github.com/dnesteryuk/vcr/blob/better_debug/spec/lib/vcr/errors_spec.rb#L113-L119>.
>    But, there may be more cases which I need to test. Most of written tests
>    are about one cassette in the stack. Should I add additional tests to
>    verify similar cases, but for the situation when we have a few cassettes?
>    Actually, the current code doesn't care how much cassettes in the stack we
>    have, therefore, I guess the current test suit is ok.
>
> Please, provide your feedback. If the changes are ok, I will create a pull
> request. Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vcr/vcr/issues/478#issuecomment-130683370>.
>



-- 
Kurtis Rainbolt-Greene, Hacker
Software Developer
1631 8th St.
New Orleans, LA
70115

**Comment by mcfiredrill** [comment]
Closing as https://github.com/vcr/vcr/pull/501 was merged.
