### ISSUE TITLE
Less debug log output

### ISSUE THREAD

**Issue by supairish** [vcr/vcr#481]
Hello!,
   When using the "debug_logger" VCR config option, the output is very hard to grok as there are literally hundreds of lines of requests that aren't really relevant to debugging your application's code.  Perhaps it's because I'm using Selenium/Chromedriver/Capybara, but 90+% of the log output seems to be Selenium requests (or maybe Capybara) talking to the app under test (setting cookies, managing sessions, executing cmds, etc).  For example in project I'll see hundreds of lines like:

```
[webmock] Handling request: [post http://127.0.0.1:9515/session/debbd244b61232898f467d6dd1cb0290/execute {"Accept"=>["application/json"], "Content-Type"=>["application/json; charset=utf-8"], "Content-Length"=>["43"], "Accept-Encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "User-Agent"=>["Ruby"]}] (disabled: false)
[webmock] Identified request type (ignored) for [post http://127.0.0.1:9515/session/debbd244b61232898f467d6dd1cb0290/execute {"Accept"=>["application/json"], "Content-Type"=>["application/json; charset=utf-8"], "Content-Length"=>["43"], "Accept-Encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "User-Agent"=>["Ruby"]}]
[webmock] Handling request: [head http://127.0.0.1:9515/shutdown {"Accept"=>["*/*"], "User-Agent"=>["Ruby"]}] (disabled: false)
[webmock] Identified request type (ignored) for [head http://127.0.0.1:9515/shutdown {"Accept"=>["*/*"], "User-Agent"=>["Ruby"]}]
```

You then have to very carefully dig through all these lines to find the actual external requests made by the app.  I thought that maybe using the "ignore_request" option would limit the logging, but it doesn't appear to.  Is there a way to limit the logging so that these type of requests don't get logged?

**Comment by krainboltgreene** [comment]
Hmm, not that I know of but I'll see what I can dig up.

**Comment by krainboltgreene** [comment]
That's the point of that option.
