### ISSUE TITLE
How can we match requests without basic auth details in VCR

### ISSUE THREAD

**Issue by loganathan-s** [vcr/vcr#484]
I am using VCR to record the external apis in Rspec, and I would like to match the requests irrespective of the basic authentication credentials, since basic authentication is dynamic in my case.

Given below the sample recorded cassette with basic auth details

https://apiuser:X9byy%5D2tluVLqi@test.com/roles.json

**Comment by krainboltgreene** [comment]
Ideologically you can't, because literally those aren't the same request. It'd be like saying "How do I make sure these humans are the same, regardless of their face."

What you can technically do is change how "equality" works. I suggest creating a new object, maybe call it `SimplisticRequestMatcher`, it knows about two requests:

``` ruby
class SimplisticRequestMatcher
  def initialize(*requests)
    @requests = requests
  end

  def matches?
    @requests.all? do |request|
      # Your condition here
    end
  end
end
```

**Comment by myronmarston** [comment]
VCR's custom request matcher feature would support this:

https://relishapp.com/vcr/vcr/v/2-9-3/docs/request-matching/register-and-use-a-custom-matcher

**Comment by mcfiredrill** [comment]
`define_cassette_placeholder` is probably the easiest way.
https://www.relishapp.com/vcr/vcr/v/2-0-0/docs/configuration/filter-sensitive-data

If you store your basic auth in the environment you could use it like this:

```
config.define_cassette_placeholder("<BASIC_AUTH>") do
  ENV['BASIC_AUTH']
end
```

**Comment by myronmarston** [comment]
Sorry, @krainboltgreene, I don't have the time to work on this.  I unassigned myself in the hope that someone else would pick this up.

**Comment by krainboltgreene** [comment]
@myronmarston It's already closed, I was giving you credit.

**Comment by myronmarston** [comment]
> @myronmarston It's already closed, I was giving you credit.

Ah. I've never seen "assigned" used that way before.
