### ISSUE TITLE
VCR Debug Message Leaking Sensitive Data

### ISSUE THREAD

**Issue by hugobast** [vcr/vcr#487]
I have this debug message printing now, I'm gonna remove the sensitive data but believe me when I say that it's still there look for `{THIS PART SHOULD BE FILTERED}`:

```
Failure/Error: expect(subject.track!).to be_success
     VCR::Errors::UnhandledHTTPRequestError:


       ================================================================================
       An HTTP request has been made that VCR does not know how to handle:
         POST https://s2s.adjust.com/revenue
         Body: app_token={THIS PART SHOULD BE FILTERED}&created_at=2015-05-
06T04%3A11%3A32Z&currency=CAD&environment=sandbox&event_token=fbv8tw&idfa=
{THIS PART SHOULD BE FILTERED}&revenue=2.0&s2s=1

       VCR is currently using the following cassette:
         - /Users/hugobastien/src/adjust/spec/fixtures/responses/revenue_success.yml
         - :record => :once
         - :match_requests_on => [:method, :uri, :body]
...
```

I have VCR set properly to filter those out and they don't appear in the cassettes yaml, but they do show up in the logs unfiltered. That's wouldn't be so bad if I wasn't running it on TravisCI. I wasn't expecting the API key to be rendered in plain text like that in the logs when it errored.

**Comment by krainboltgreene** [comment]
This is an interesting problem to solve, because there are two ways to get
around it:

  1. Never make real requests with VCR, just use it as a fixture library.
  2. Change VCR write the sensitive layer around logging

Frankly I'm of the opinion that 2 is not the right choice and here's why:

  1. It makes it harder to debug (am I using the right secret? is it the
right place? is it the right format?)
  2. Logs really should only be printing locally, where it's safe to log
  3. It's more code that I have to consider

But I realize that sucks for you because I've basically said "Hey, go do
some extra work or do things different from what you're doing." So can you
give me some insight into why your logger is reporting in a insecure
environment?

**Comment by hugobast** [comment]
Thanks for the quick reply,

Here's some insight into how it happened, I now know that it should have been preventable more on that later. 

I added TravisCI hooks on the repository. I also gave TravisCI the real sensitive information as environment variables, not really thinking wether it needed it or not at all. The specs ran, replaying the requests and obviously Travis servers timezone is not the same as my dev machine and those tests failed with `VCR::Errors::UnhandledHTTPRequestError` printing everything it had about the request including those environment variables used in the body.

I'm not saying it should or shouldn't be addressed but it's entirely possible to leak sensitive information if someone is using TravisCI on a public repo with sensitive information configured inside environment variables.

Here's what I know that would have prevented it. The tests ran by TravisCI never really needed the real sensitive information (in this case an API secret) they would have been none the wiser with anything since replaying the request with different sensitive information works just the same. I went and deleted the sensitive information from travis and put new environment variables with fake stuff in it.

Thanks!

**Comment by hugobast** [comment]
It's only ever a problem if you have included body in the matchers: https://github.com/vcr/vcr/blob/master/lib/vcr/errors.rb#L91-L93

I can try a stab at a PR if you think it's worth it.

**Comment by krainboltgreene** [comment]
Alright so I sat on this for a while and decided that basically my opinion
is that if you're shipping sensitive information to your CI server you
should be very sure you're not going to have any tests that fail in the
network department.

With that said: it's a code repository not an opinion box so if you want to
do a PR I'll look it over.

On Wed, May 6, 2015 at 12:13 PM, Hugo Bastien <notifications@github.com>
wrote:

> It's only ever a problem if you have included body in the matchers:
> https://github.com/vcr/vcr/blob/master/lib/vcr/errors.rb#L91-L93
>
> I can try a stab at a PR if you think it's worth it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vcr/vcr/issues/487#issuecomment-99541216>.
>



-- 
Kurtis Rainbolt-Greene, Hacker
Software Developer
1631 8th St.
New Orleans, LA
70115

**Comment by hugobast** [comment]
Yeah been rethinking all this over, and I looked at the code involved for the debugging statements. It's sufficiently removed from the part that does the filtering to be too much of a pain to implement. 

That being said I could just not have given travis the right keys, the test cared that _a_ value would be present for the environment variable but not that the real value was available.

Thanks for your responses Kurtis, cheers!
