### ISSUE TITLE
Specify re-recording of a specific spec (or group) using rspec metadata

### ISSUE THREAD

**Issue by ToadJamb** [vcr/vcr#498]
I have to be missing something. I often find myself wanting to re-record a specific spec (or group of specs within a file), while playing back cassettes for the remaining specs. This happens most often when writing a new spec.

Adding the following code gives me the behavior I want, but it seems like this is something VCR should support and I'm just missing it. What's the right way to do this?

``` ruby
# spec/support/vcr.rb
RSpec.configure do |config|
  config.before(:each, :record) do |example|
    VCR.current_cassette.instance_variable_set(:@record_mode, :all)
  end
end
```

**Comment by krainboltgreene** [comment]
Hey @myronmarston, you have the knowledge here. Care to pop in?

**Comment by myronmarston** [comment]
The normal way to do this is to pass `:record => :all` with your cassette options to `VCR.use_cassette` or `VCR.insert_cassette`:

``` ruby
VCR.use_cassette "name", :record => :all do
  # ....
end
```

If you are using VCR's RSpec metadata integration, then you can pass cassette options in the metadata:

``` ruby
it "uses VCR", vcr: { record: :all } do
   # ...
end
```
