### ISSUE TITLE
Configuration for VCR disabling WebMock disable_net_connection! 

### ISSUE THREAD

**Issue by bytenel** [vcr/vcr#499]
Not sure if I should report this bug to you guys or to WebMock but since I found it while using VCR I figured I would start here and see what happens! 

So in my VCR config I have:
```
VCR.configure do |c|
  c.allow_http_connections_when_no_cassette = true
  c.cassette_library_dir = Rails.root.join('spec', 'vcr_cassettes')
  c.hook_into :webmock
  c.ignore_localhost = true
  c.configure_rspec_metadata!
  c.default_cassette_options = { match_requests_on: [:method] }
end
```

the allow_http_connections_when_no_cassette forces WebMock to allow those connections even if I manually state (for certain tests where I do want connections disabled no matter what) that I want http connections disabled. I guess this is kind of expected? But it was jarring for me since I wanted to do this in this specific instance and clean it up on my own. Also, it was a bit hard to debug since when I run the disable command for WebMock I don't get any sort of information from VCR about what is going on or why the connection is still occurring. Again, I'm not sure if that is just from WebMock or from VCR directly.

**Comment by krainboltgreene** [comment]
Looking into this as soon as I can, sorry it took me so long to get back to you @bytenel.

**Comment by bytenel** [comment]
No worries! Thanks for the follow up!!

**Comment by galori** [comment]
@bytenel I think you've ran into a fairly common problem. VCR wasn't designed to play nice with uses of Webmock outside of VCR - as in, if you want to manually stub some requests with webmock but not use VCR for them.  

VCR was designed to take over your entire test suite and record and play back all HTTP requests.

However, this issue discusses several solutions to this problem: https://github.com/vcr/vcr/issues/146

Including a way to disable VCR for a single test (blacklist), or conversely a way to switch to a whitelist mode where you enable VCR for certain tests only.

Finally if you follow the link from the last comment to the gist, that is a comprehensive approach to allowing VCR, Webmock and live HTTP requests to all live in harmony in as single test suite.

I'm going to close this but please re-open if this doesn't solve your problem and provide additional specifics.

**Comment by bytenel** [comment]
Sounds good, I will look into it when I get time. We found a solution in the interim that works for us and seems to do all of what you stated (WebMock, VCR and live http all in one suite). It would be nice however to have some of that documented in the VCR README since I think it is a fairly common use case for this software, especially when integrating into existing testing suites. I'd be happy to work on a pull request for that.
