### ISSUE TITLE
gitter chat?

### ISSUE THREAD

**Issue by mcfiredrill** [vcr/vcr#505]
I think it might be nice to have a gitter chat to discuss maintaining this project. Anyone interested?
I know we have the mailing list but a chatroom might be nice as well.

I can't create one myself since I'm not the owner of this repository.
http://gitter.im

**Comment by jessmartin** [comment]
:+1: this! Had some questions, and a newsgroup just feels heavy and discourages from posting / replying.

It's worked really well on the [Neo4jrb](http://github.com/neo4jrb/neo4j) project: http://gitter.im/neo4jrb/neo4j

**Comment by sigmavirus24** [comment]
There's already an IRC room. Do we really need *another* avenue for discussion? Also, why use Gitter? There are much better, much less annoying platforms.

**Comment by mcfiredrill** [comment]
@sigmavirus24 Ah nice, I didn't know there was an IRC.
Could add it to the README?

**Comment by sigmavirus24** [comment]
If it isn't there, yes. Let's add it. It's just `#vcr` on `irc.freenode.net`.

**Comment by jessmartin** [comment]
IRC is great! Also didn't know about it.

On Monday, August 31, 2015, Ian Cordasco <notifications@github.com> wrote:

> If it isn't there, yes. Let's add it. It's just #vcr on irc.freenode.net.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vcr/vcr/issues/505#issuecomment-136545932>.
>


-- 
Jess Martin
http://jessmart.in

**Comment by krainboltgreene** [comment]
IRC is painful for newbies, I'm still considering gitter. I've made the room, but seeing how long I actually stay.

**Comment by krainboltgreene** [comment]
@sigmavirus24 We actually removed the IRC channel some time ago: 057598ec393e742953d17d54fc65c1acedfa1bd0

**Comment by mcfiredrill** [comment]
@krainboltgreene Thanks!
Gitter chat is here if anyone is interested
https://gitter.im/vcr/vcr

**Comment by sigmavirus24** [comment]
@krainboltgreene well people still use the IRC channel, so it's not totally unreasonable to keep around. But not my decision. I'll continue to sit around in there and help people out when necessary.
