### ISSUE TITLE
Gearman Implementation

### ISSUE THREAD

**Issue by nasospsa** [vcr/vcr#510]
Is there something like that? When I can stub automatically gearman responses?

**Comment by krainboltgreene** [comment]
I need more details :o

**Comment by galori** [comment]
I'm assuming you're referring to this project, yes? http://gearman.org/

VCR can record and re-play and HTTP traffic going in and out of your application while running your test suite, as long as it is 

1. in Ruby 
2. uses a supported testing framework (such as rspec, testunit, minitest)
3. Uses a supported HTTP library (such as NetHTTP, Faraday, HTTParty)

See http://www.relishapp.com/vcr/vcr/docs for the full list of libraries that VCR supports, which is the majority of libraries in use by Ruby developers.

Are you making calls to Gearman from Ruby using one of the supported libraries? If so, it can work. If not, maybe. Let us know what you're using to interface with Gearman and we can provide more specifics.

I'm closing this ticket but please re-open with any follow up questions or info.

**Comment by nasospsa** [comment]
Sure. I am using [gearman-ruby](https://github.com/johnewart/gearman-ruby) for interacting with Gearman.

Specifically we are interacting with a kind of API with JSON requests and responses.

We have implemented a mechanism very similar to what VCR does.
We are stubbing the Gearman requests to try and see if there's already a document with that specific data(as JSON). If not we request them, and store them as the file we sought.
 
This way we don't have to request the data while tests are running on a CI env

**Comment by galori** [comment]
What matters is what underlying networking library gearman-ruby uses.

From what I can tell, it uses TCPSocket:

https://github.com/johnewart/gearman-ruby/blob/master/lib/gearman/connection.rb

(correct me if I'm wrong if it i uses anything else)

VCR does not support socket communications and therefore this will not work with VCR. See https://stackoverflow.com/questions/9762141/unable-to-record-whois-requests-with-vcr

Looks like there is a library: https://github.com/robforman/tcr that attempts to do what VCR does but for TCP Sockets. I've never used it so I can't vouch for how well it works.

If you can communicate using standard HTTP (using Net::HTTP for example) - then you'd be able to use VCR.
