### ISSUE TITLE
Compressed extension is gz but they are not gzipped

### ISSUE THREAD

**Issue by raszi** [vcr/vcr#526]
Therefore the standard tools like zless, zcat cannot open them.

Please consider to name them differently or use a different compression algorithm.

**Comment by extemporalgenome** [comment]
Ideally we should compress new cassettes using actual Gzip, but fall back to _decoding_ with Zlib if the Gzip decode fails.

**Comment by raszi** [comment]
[Pigz](madler/pigz) uses zz for Zlib compressed files and gz for Gzip compressed files.
