### ISSUE TITLE
Add warning - do *NOT* put cassettes in test/fixtures if using Rails minitest

### ISSUE THREAD

**Issue by david-a-wheeler** [vcr/vcr#527]
The documentation should prominently warn people to *NOT* put vcr_cassettes inside the 'test/fixtures' directory when using Rails and minitest.

It *seems* logical to do this, but as noted in <http://guides.rubyonrails.org/testing.html>, "Rails by default automatically loads all fixtures from the test/fixtures folder for your models and controllers test."  The result: The system will try to load the vcr cassettes as models, causing mysterious error messages.

I decided to use 'test/vcr_cassettes/' which works fine (because I wanted all test materials inside test/).

A little warning might save debugging time for someone else...!

**Comment by krainboltgreene** [comment]
Haaaaa...Whew.

@david-a-wheeler I really appreciate this issue. Can you make a PR? Otherwise I'll get to it EOD.

**Comment by Edouard-chin** [comment]
I believe this issue was already reported and fixed on https://github.com/vcr/vcr/issues/9

**Comment by david-a-wheeler** [comment]
No, issue #9 does not fix this.

I looked at the current README at <https://github.com/vcr/vcr/blob/master/README.md>. Nothing says something like "do NOT put vcr_cassettes inside the 'test/fixtures' directory when using Rails and minitest, because the fixtures will be loaded as models."

I'll see if I can make a pull request to show what I mean.

**Comment by david-a-wheeler** [comment]
Please see pull request #543 - https://github.com/vcr/vcr/pull/543 - which proposes one way to warn people.
