### ISSUE TITLE
Having trouble using VCR with RSpec - VCR::Errors::UnhandledHTTPRequestError

### ISSUE THREAD

**Issue by vmcilwain** [vcr/vcr#554]
Note: This is a cross post from the VCR Google Group. I saw a post that said it was preferred to send questions and issues here.

Sorry if this offends anyone.

-
Hello all,

I am having trouble using the VCR with RSpec. I have used it before with success but I am struggling now to get past this error.

I am attempting to record 2 calls to remote services (twitter, tinyurl). VCR seems to handle things fine when the code makes a call to twitter but throws an error the moment the code tries to make a call to tinyurl. Even after deleting all the cassettes, this error still pops up.

I noticed that the 3rd bullet point said that the current mode is :once so I am not able to add any new request but I did delete my cassettes and the error still pops up.

Any help would be greatly appreciated.

Here is what I have in my spec/rails_helper.rb
```
VCR.configure do |c|
  c.cassette_library_dir = 'spec/cassettes'
  c.hook_into :web mock
  c.configure_rspec_metadata!
  c.ignore_localhost = true
end
```

Here is the error I am getting:

```
VCR::Errors::UnhandledHTTPRequestError:

       ================================================================================
 
       An HTTP request has been made that VCR does not know how to handle: 

         POST http://tinyurl.com/api-create.php?url=http://www.mysite.direct/blogs/ut-accusantium-fuga-excepturi-recusandae 

       VCR is currently using the following cassette: 
         - /Users/vmcilwain/rails/vell/spec/cassettes/BlogsController/POST_create/a_successful_creation_posting_to_twitter/sets_flash_success_.yml 
           - :record => :once 

           - :match_requests_on => [:method, :uri] 

       Under the current configuration VCR can not find a suitable HTTP interaction

       to replay and is prevented from recording new requests. There are a few ways

       you can deal with this: 

         * If you're surprised VCR is raising this error 

           and want insight about how VCR attempted to handle the request, 

           you can use the debug_logger configuration option to log more details [1]. 

         * You can use the :new_episodes record mode to allow VCR to 

           record this new request to the existing cassette [2]. 

         * If you want VCR to ignore this request (and others like it), you can 

           set an `ignore_request` callback [3]. 

         * The current record mode (:once) does not allow new requests to be recorded 

           to a previously recorded cassette. You can delete the cassette file and re-run 

           your tests to allow the cassette to be recorded with this request [4]. 

         * The cassette contains 2 HTTP interactions that have not been 

           played back. If your request is non-deterministic, you may need to 

           change your :match_requests_on cassette option to be more lenient 

           or use a custom request matcher to allow it to match [5]. 

       [1] https://www.relishapp.com/vcr/vcr/v/3-0-1/docs/configuration/debug-logging 

       [2] https://www.relishapp.com/vcr/vcr/v/3-0-1/docs/record-modes/new-episodes

       [3] https://www.relishapp.com/vcr/vcr/v/3-0-1/docs/configuration/ignore-request 

       [4] https://www.relishapp.com/vcr/vcr/v/3-0-1/docs/record-modes/once 

       [5] https://www.relishapp.com/vcr/vcr/v/3-0-1/docs/request-matching 

       ================================================================================

```

**Comment by mcfiredrill** [comment]
Thanks for reporting this. 

* Are you sure the URI is the same as the time you recorded the cassette? 

* is there any way you are you able to share a full reproducible test case? 

iPhone$B$+$iAw?.(B

2016/02/24 9:30$B!"(BVell - [I am available to join projects.] <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by vmcilwain** [comment]
@mcfiredrill 

Thanks for the response.

My repo / spec that is showing me this problem is:
https://github.com/vmcilwain/vell/blob/bug/fix-vcr-cassettes/spec/controllers/blogs_controller_spec.rb

The interesting thing is the URI is the same aside from the parameters being submitted.

1. TinyURL URI is the same aside from the parameters to be converted
2. Twtitter URI is the same aside from the parameters to be posted

I suspect that I have the same issue with twitter but I am hitting TinyURL first. Here is how I reproduce the error.

1. I delete the cassettes and run my specs. Everything passes.
2. I immediately re-run my specs and I get this error.

The objects I create with factory girl use faker to generated the data so the submitted parameters are different each time a new object is created.

What I will do when I get a chance is:

1. delete the cassettes
2. modify my spec to generate a factory with hard coded values
3. run my tests to see if they pass
4. immediately re-run my tests to see if this error pops up again

I will let you know how it goes.

**Comment by mcfiredrill** [comment]
By parameters, do you mean the query parameters in the URI? Because I believe that would probably cause a cassette mismatch.

**Comment by vmcilwain** [comment]
Yes thats exactly what I mean. Thats the only thing I can think of that would cause this in the way that its happening. So if I hard code the query parameters so that its always the same as what the cassette is expecting then things should work without any issue. Thats my guess.

**Comment by mcfiredrill** [comment]
If you would like to ignore the query parameters when matching, you might try using `uri_without_param`.
https://www.relishapp.com/vcr/vcr/v/3-0-1/docs/request-matching/uri-without-param-s

So if you want to ignore the `url` param in your tinyurl URI, you could put this in your configure block:
```
  c.default_cassette_options = {
    :match_requests_on => [:method,
      VCR.request_matchers.uri_without_param(:url)]
  }
```

**Comment by vmcilwain** [comment]
Thats a much better way to do it. I appreciate the suggestion.

**Comment by mcfiredrill** [comment]
No problem, I hope that helps.

**Comment by vmcilwain** [comment]
Yep that definitely did it. I was able to run the tests to create the cassettes. Re-run the tests and I didn't get the error.

Thanks again for the help!
