### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by NewAlexandria** [vcr/vcr#556]
I don't understand the license as based on any standard, like the MIT license, APGL, etc.  

Can you clarify which license this is released under?  Legal departments in some large companies are tediously focused on whether every piece of code could fall under copy-left.

Thank you

**Comment by nikolas** [comment]
The license here: https://github.com/vcr/vcr/blob/master/LICENSE is identical to what's commonly referred to as the "MIT" license, but what the FSF calls the Expat license: http://directory.fsf.org/wiki/License:Expat

> This is a lax, permissive non-copyleft free software license, compatible with the GNU GPL. It is sometimes ambiguously referred to as the MIT License.

> For substantial programs it is better to use the Apache 2.0 license since it blocks patent treachery.

**Comment by NewAlexandria** [comment]
@nikolas thanks for that clarification and nuance.  That won't solve every legal dept.'s concerns, but I think it paints the right path for what is at heart and intended.  

Much appreciated.

**Comment by jamie** [comment]
@NewAlexandria Also see https://github.com/vcr/vcr/blob/master/vcr.gemspec#L16

**Comment by mcfiredrill** [comment]
@nikolas Thank you for your help !

**Comment by NewAlexandria** [comment]
I think this suites needs at this time, and so I'll close this issue.  If anyone needs something more elaborate, this can be reopened. :+1:
