### ISSUE TITLE
How to completely turn off VCR????????

### ISSUE THREAD

**Issue by chris1248** [vcr/vcr#559]
We use VCR here to handle a few external dependencies. But in some cases we have integration tests where we hit the real servers. Those tests can NOT use VCR. But I can find no mechanism to just completely, abjectly and categorically turn off this beast.

How do you do it?

**Comment by krainboltgreene** [comment]
Largely @chris1248 the issue sounds like you're automatically doing VCR for every spec. I would advise against this and instead use VCR specifically for specs where you care about it, either manually or with a tag.

**Comment by chris1248** [comment]
Correct. So How do I turn if off for specs I don't care about.

**Comment by krainboltgreene** [comment]
If you really want to approach it that way, I suggest this: https://relishapp.com/vcr/vcr/v/3-0-1/docs/configuration/ignore-request

Where you use `ignore_request { true }`.

**Comment by mcfiredrill** [comment]
@chris1248 Have you tried `turn_off` or `turned_off` (takes a block) ?
https://www.relishapp.com/vcr/vcr/v/1-11-3/docs/cassettes/error-for-http-request-made-when-no-cassette-is-in-use

```
VCR.turn_off!
```
or

```
VCR.turned off do
end
```

**Comment by krainboltgreene** [comment]
Holy crap, that's a thing?

**Comment by chris1248** [comment]
That's totally awesome mcfiredrill.
