### ISSUE TITLE
VCR Future & Ruby Together

### ISSUE THREAD

**Issue by krainboltgreene** [vcr/vcr#560]
@vcr/core @vcr/extras

So recently I've been hired to work on rubygems, via Ruby Together.

[Ruby Together](https://rubytogether.org/) is a community-funded organization devoted to maintaining rubygems.org, bundler, and gem. These are integral tools to our community and ruby developers would be pretty fucked without those tools. Because of this work however (and my own day job) I haven't had much time to work on vcr directly. I'm moving @mcfiredrill to admin level rights along with me to handle further issues.

One thing I'd like to bring forward is that I'm currently talking to the lead of Ruby Together, @indirect, about a further subgrouping of ruby tools, including things like vcr. Specifically efforts for these libraries would be about best practices for maintaining libraries and awareness to the larger community. I'm considering this largely because I believe Ruby Together's members and community are some of the best library maintainers out there and they have a lot of knowledge they can impart.

Why does this involve you? As part of this change, VCR would be able to accept money from people who depend on it, and be able to use that money to pay developers who work on it, in a public and transparent way. I'm currently in talks with a service provider doing this and I have high hopes.

VCR is invaluable not just to our community, but the larger web development community and @myronmarston's work should be kept healthy and moving forward. Let me know your thoughts.

**Comment by galori** [comment]
This is awesome. 

BTW I work for Stitch Fix, which is a sponsor / [Corporate Member](https://rubytogether.org/members) of Ruby Together. 

How is this going so far? Is there anything you could use help with as far as getting VCR ramped up with this? (Even administrative)

**Comment by lynnco** [comment]
I work with @krainboltgreene on Ruby Together, so I'll be creating (and implementing) a few features

**Comment by mcfiredrill** [comment]
I'm pretty fuzzy on the details but I believe some funds are now coming through Open Collective.
https://twitter.com/opencollect/status/768441801803984896

https://opencollective.com/vcr

I was talking to @krainboltgreene on twitter about this and we agreed we should discuss how we are going to distribute the funds to contributors in the open as much as possible.

**Comment by krainboltgreene** [comment]
@galori Hey there, sorry I didn't respond to this, been a bit busy. 

This is a good time to give an update as well: The team at I Done This has officially put down money via Open Collective, you can see their donation and others on the link @mcfiredrill supplied.

I believe we have a steady amount coming in and will have some in the future and now that means how to handle the money we have at our disposal. Luckily OC has a nifty feature that lets me transparently give out the money as needed. One tactic we're discussing is paying individual pull requests for their work. We still need to decide how much and the scale, but that's open for discussion.

**Comment by krainboltgreene** [comment]
No one cared, it didn't matter.
