### ISSUE TITLE
Wrong cassette used

### ISSUE THREAD

**Issue by tak1n** [vcr/vcr#561]
In one of our projects we get test order dependent failures in conjunction with vcr.
Basically what happens when 2 specs run after each other the latter one uses the response of the former cassette instead of its own cassette response.

We are using rspec with vcr metatag for smoother integration.
Here is our VCR setup:

```ruby
VCR.configure do |c|
  c.cassette_library_dir = 'spec/fixtures/.cassettes'
  c.hook_into :webmock # or :fakeweb
  c.allow_http_connections_when_no_cassette = true
  c.configure_rspec_metadata!

  if ENV['WITH_NETWORK']
    c.default_cassette_options = { re_record_interval: 864_000, record: :all }
  else
    c.default_cassette_options = { re_record_interval: 864_000 }
  end

  c.register_request_matcher :xing do |request1, request2|
    requests = [request1, request2].map { |r| URI(r.uri).to_s.sub(/&oauth_nonce=(\w)*&/, '') }
    requests.first == requests.second
  end
end
```

I also tried `rspec --bisect` which gave me following reproduction command: 
```
rspec './spec/integration/feedback/flickr_spec.rb[1:1:1:1]' './spec/integration/publish/flickr_spec.rb[1:1:1:1]'
```

This reproduction script fails like it should, but when running it again with `WITH_NETWORK` enabled (which enables rerecording of cassettes) all is well. Also running it afterwards without rerecording everything passes.

We are running the single integration spec when developing a feature, therefore I somehow have the feeling this occurrs when you record cassettes standalone but when you use them in the whole spec suite they are failing and you have to rerecord them. But I have really no idea if this is a bug or we are doing something wrong here.

Sorry that I can not provide a reproduction repo (the repo where the failures happen is not open source yet). I will try to make a simple reproduction repo in the next few days.

**Comment by mcfiredrill** [comment]
A reproduction repo would be great.

Its hard to say anything without seeing any of the tests you say are failing. I have no idea how you are using `VCR.use_cassette`, whether you are using that custom request matcher, etc.

**Comment by tak1n** [comment]
Can not reproduce this in anyway. Therefore closing for now, if it occurs again and I have a reliable reproduction I will reopen it.
