### ISSUE TITLE
Remove LGTM.co

### ISSUE THREAD

**Issue by mcfiredrill** [vcr/vcr#563]
I like the idea of using tools to assist development, but at this point I think LGTM.co is hindering development more than helping it. There's a number of PRs open which I can't merge due to not having enough LGTM comments, or what appears to me to be LGTM not working here: https://github.com/vcr/vcr/pull/539

I can imagine if there were more maintainers this tool could work a bit better. For now however, I think its blocking more than helping. 

I have access to remove it now, but before I take action I'd love to hear thoughts from other folks on this.

**Comment by krainboltgreene** [comment]
Agreed.

**Comment by mcfiredrill** [comment]
Thanks for all your work on this gem, @krainboltgreene . 
I removed the integration. I think I may have to reopen some pull requests to have them merged.

**Comment by krainboltgreene** [comment]
I turned off the service.

> I think I may have to reopen some pull requests to have them merged.

Branches will need to be updated anyhow, as something has changed in core.

**Comment by mcfiredrill** [comment]
Thanks @krainboltgreene !
