### ISSUE TITLE
can we get all cucumber scenarios to use vcr and not bother with tags?

### ISSUE THREAD

**Issue by tansaku** [vcr/vcr#568]
I'd like all my cucumber features to use VCR - is there a simple config for this that would allow us to avoid having to specify a tag for every feature?

**Comment by MothOnMars** [comment]
I accomplished this by adding an `Around` hook to `features/support/hooks.rb`:
```ruby
Around do |scenario, block|
  VCR.use_cassette("#{scenario.feature.name}/#{scenario.name}") do
    block.call
  end
end
```
References:
https://github.com/cucumber/cucumber/wiki/Hooks
https://relishapp.com/vcr/vcr/v/3-0-3/docs/test-frameworks/usage-with-cucumber
