### ISSUE TITLE
WebMock 2.0 support.

### ISSUE THREAD

**Issue by bblimke** [vcr/vcr#570]
This is a heads up before the release of WebMock 2.0
Version 2.0 is partially backwards incompatible with 1.x. It's currently released as 2.0.0.beta1

All the changes are listed here https://github.com/bblimke/webmock/blob/2.0/CHANGELOG.md#200

Unless there are issues found, I'd be keen to release it this week.

**Comment by ujh** [comment]
It would be great if VCR could handle the basic auth issue. Right now I'd have to throw away the old cassettes if they use basic auth as they aren't stubbed out anymore.

**Comment by bblimke** [comment]
@ujh it's more a WebMock's fault than VCR's, since WebMock was providing request signatures to VCR. These request signatures were incorrect as they moved credentials from auth header to userinfo in the url.

Webmock now does what it should have been doing from beginning, but that's not compatible with the data recorded in old cassettes. Not sure how to resolve that without modifying the cassettes manually (moving credentials from userinfo back to auth header) or re-recording them.

It's one step closer to recording real raw request data, which has been an issue referenced from VCR for a long time.

I'm not sure it's a good idea to handle that in VCR since VCR would have to introduce the compatibility mapping that WebMock just removed.

**Comment by ujh** [comment]
I see. Is there an easy way to transform from the old to the new way? I should be able to regenerate most cassettes, but for some it would be super nice if I could keep them.

**Comment by bblimke** [comment]
Yes.

cassettes are just yaml files.

you can simply remove userinfo from the `url` entries and add a new "Authorization" header with "Basic ..." value.

Perhaps it would be worth writing a converter script that reads casette yaml file, does the replacement (userinfo => authheader) and overwrites the file with new data. It would be useful for everyone else.

**Comment by janraasch** [comment]
Do we also need to call

```ruby
WebMock.enable!
```

manually now? Or will this be part of `lib/vcr/library_hooks/webmock.rb`?

**Comment by bblimke** [comment]
I'll let VCR maintainers to comment on that but I'd imagine that VCR would enable Webmock automatically.

**Comment by bblimke** [comment]
btw. latest version of WebMock 1.x, 1.24.6 is still compatible with VCR so anyone can just lock webmock to "< 2.0.0" temporarily until all issues are resolved with VCR compatibility.

**Comment by ujh** [comment]
Thanks. I'll see if I can come up with a script.

**Comment by glaszig** [comment]
[there you go](https://gist.github.com/glaszig/9170b1cf2186674faeead74a68606c5d). 

- adds auth header (`Authorization: <%= Base64.encode64("user:password").chomp.inspect %>`)
- removes `userinfo` data from request uri
- converts yaml strings (`! 'foo'` into `"foo"`)

**Comment by ujh** [comment]
Thanks, however there are two problems with your solution:

1. That's not a proper basic auth header
1. It only works with valid URIs. If you use the `fetch_sensitive_data` feature of VCR to replace parts of the URI you might end up with URIs that aren't valid.

Here's my script (tested on my code base): https://gist.github.com/ujh/594c99385b6cbe92e32b1bbfa8578a45

**Comment by glaszig** [comment]
thanks, @ujh. i fixed (1) - was probably too late over here - but i don't care about (2) for my use-case.

**Comment by mcfiredrill** [comment]
What I gather from this conversation so far is that we might possible want to call `WebMock.enable!` somewhere in the VCR code.

It would be nice to provide a nicer upgrade path but I think for most people re-recording cassettes is not a *huge* deal, I could be wrong though.

I'm not sure of any other incompatibilities yet.

**Comment by mcfiredrill** [comment]
I've upgraded most of my apps using VCR to webmock 2.0 without any issues. 
However the build for VCR itself is failing all over the place currently. 😭 
https://github.com/vcr/vcr/pull/573

**Comment by mcfiredrill** [comment]
As long as this doesn't break any users' existing workflows, I'm thinking of calling `WebMock.enable!` when `hook_into :webmock` is called.
This should prevent users from having to call it themselves, which is convenient as well as fixes our test suite.

https://github.com/vcr/vcr/pull/579

**Comment by ricardoxvpn** [comment]
+1 @bblimke

**Comment by mcfiredrill** [comment]
I merged #579, and will release a patch version shortly.

**Comment by mcfiredrill** [comment]
I just pushed version 3.0.2 of VCR, the includes enabling webmock automatically when `hook_into :webmock` is called.
https://rubygems.org/gems/vcr/versions/3.0.2
Would love to hear any feedback about it.

**Comment by mcfiredrill** [comment]
Webmock 2 support added in 3.0.2.
