### ISSUE TITLE
Using Regex with version 2.9.3

### ISSUE THREAD

**Issue by AlanDonohoe** [vcr/vcr#572]
I am trying to follow the example from version 1.7.1, where you can use regex to match dynamic urls (here: https://www.relishapp.com/vcr/vcr/v/1-7-1/docs/cassettes/request-matching#use-a-regex-for-the-request-uri) 
eg: 
uri: !ruby/regexp /^http:\/\/bar.com\/foo/ 
but I am using version 2.9.3 and when I run the spec that hits the cassette I get a invalid URL error.

Is regex still supported in later versions?

**Comment by mcfiredrill** [comment]
I'm not sure if regex is still supported, did you check the 2.9.3 docs?
You might try using a custom request matcher:
https://relishapp.com/vcr/vcr/v/3-0-1/docs/request-matching/register-and-use-a-custom-matcher

**Comment by AlanDonohoe** [comment]
Hi,

I couldn't see any mention of regex after those 1.7.1 docs but it's such a shame if it's been taken out as it's perfect for our use case.

I did try custom matching and it did work with the dynamic url I wanted to match but then other urls who were similar also used the custom matcher but didn't get a match... when they should of used the other regular, pre-recorded, matches in the cassette...

**Comment by mcfiredrill** [comment]
It was removed in 2.0. https://github.com/vcr/vcr/pull/470#issuecomment-69643361

Since you can use a regex in the custom matcher (or really any code you want) you should be able to achieve the same functionality.

 If you could share some code I could try to help more, but its hard to debug your problem without seeing any code.

**Comment by AlanDonohoe** [comment]
Thanks so much for your help on this... 

I have created two matchers which will match different calls in the same execution of one spec:

```
c.register_request_matcher :stripe_random_customer_matcher do |request_1, request_2|
    /^https:\/\/api\.stripe\.com\/v1\/customers\/cus_(\w){14}$/ === request_1.uri
end
```
 - this matches any call to: https://api.stripe.com/v1/customers/cus_14_random_chars

I think that's working...

The other custom matcher is:

```
c.register_request_matcher :stripe_random_card_matcher do |request_1, request_2|
  /^https:\/\/api\.stripe\.com\/v1\/customers\/cus_(\w){14}\/cards\/card_(\w){24}$/ === request_1.uri
end
```
Which matches any call to: https://api.stripe.com/v1/customers/cus_14_random_chars/cards/card_24_random_chars

I have them running in the same spec like this:

```
VCR.use_cassette('user_changes_payment_details_1', :match_requests_on => [:method, :stripe_random_customer_matcher, :stripe_random_card_matcher]) do
...
```

What seems to happen is the url being requested matches the regex in stripe_random_customer_matcher which gets called first and returns true, then stripe_random_card_matcher gets called and returns false. 

Then I get the error from VCR:
```
Failure/Error: Unable to find matching line from backtrace
     VCR::Errors::UnhandledHTTPRequestError:
       An HTTP request has been made that VCR does not know how to handle:
```

I'm a bit stumped....

**Comment by mcfiredrill** [comment]
I think for `match_requests_on`, its all or nothing. 
If one of them fails, it won't match and will raise `VCR::Errors::UnhandledHTTPRequestError`.

If you are going to use them both at the same time, maybe its easier to just merge the matchers into one that just ORs the two regexes, I'm not sure though.

```
c.register_request_matcher :stripe_random_customer_matcher do |request_1, request_2|
    /^https:\/\/api\.stripe\.com\/v1\/customers\/cus_(\w){14}$/ === request_1.uri ||
          /^https:\/\/api\.stripe\.com\/v1\/customers\/cus_(\w){14}\/cards\/card_(\w){24}$/ === request_1.uri

end
```
