### ISSUE TITLE
version 4.0

### ISSUE THREAD

**Issue by mcfiredrill** [vcr/vcr#578]
This is an issue to track the major breaking changes happening in version 4.0.

- [x] remove fakeweb support
- [x] remove VCR::RSpec::Macros https://github.com/vcr/vcr/issues/180#issuecomment-8391651
- [x] drop ruby 1.9.3 support

**Comment by mcfiredrill** [comment]
- [ ] allow non lantin characters in filename  https://github.com/vcr/vcr/pull/585

**Comment by ecnalyr** [comment]
> remove VCR::RSpec::Macros 

Do you mean to completely remove the [already-deprecated](https://github.com/vcr/vcr/pull/224) `Macros` module, or is there more stuff that needs to be deprecated somewhere else first?

I don't think there is anything left of the `Macros` module that isn't deprecated, but I wanted to be sure I understood.

**Comment by mcfiredrill** [comment]
@ecnalyr It looks like VCR::RSpec::Macros is already in lib/vcr/deprecations.rb with the appropriate deprecation warnings being issued, so I don't think there is anything else that should be deprecated before we remove it in 4.0. 

Is there anything else related to Macros you thought should be deprecated before we remove it?

**Comment by ecnalyr** [comment]
> Is there anything else related to Macros you thought should be deprecated before we remove it?

No, was just wanting to make sure I understood the scope.

**Comment by mcfiredrill** [comment]
PR to remove fakeweb
https://github.com/vcr/vcr/pull/640

**Comment by paul** [comment]
Dropping fakeweb is pretty much required to work in Ruby 2.4.x. How is progress towards those other two tasks? Any chance of a release without them?

**Comment by mcfiredrill** [comment]
Should we remove typhoeus support as well?
https://github.com/vcr/vcr/issues/464#issuecomment-68910577

**Comment by mcfiredrill** [comment]
Hi its been awhile but I want to release 4.0 soon if that's cool, because I want to use https://github.com/vcr/vcr/pull/585

**Comment by krainboltgreene** [comment]
Ready when you are.

**Comment by mcfiredrill** [comment]
Released 4.0.0 this morning 🌞
