### ISSUE TITLE
Using insert_cassette vs. use_cassette

### ISSUE THREAD

**Issue by tomrossi7** [vcr/vcr#584]
Using MiniTest, VCR 3.0.3 and WebMock 2.0.3, I can no longer use insert_cassette. When I run the following code, it doesn't record anything:

```
    VCR.insert_cassette("something")
    # make http requests
    VCR.eject_cassette
```
But when I use the alternative method passing a block, it works:

```
     VCR.use_cassette("something") do
       # make http requests
    end
```

I prefer to use the insert_cassette method since I can invoke that in my test setup.

**Comment by mcfiredrill** [comment]
Hi, 

I created a fresh rails app and was able to get this working. Can you provide a reproduction script?

**Comment by mcfiredrill** [comment]
```
♫tony@moguya ~/src/vcr-minitest$ cat test/models/hey_test.rb 
require 'test_helper'
require 'net/http'

class HeyTest < ActiveSupport::TestCase
  test "the truth" do
    VCR.insert_cassette("something")
    response = Net::HTTP.get_response("google.com", "/", 80)
    VCR.eject_cassette
  end
end
```
```
♫tony@moguya ~/src/vcr-minitest$ wc -l fixtures/vcr_cassettes/something.yml 
      38 fixtures/vcr_cassettes/something.yml
```

**Comment by tomrossi7** [comment]
I swear it wasn't working! I'm not sure what I did wrong before, but thanks!

**Comment by mcfiredrill** [comment]
Is it working now? 
Feel free to reopen if you have the issue again. :)
