### ISSUE TITLE
Disabling WebMock before initializing VCR

### ISSUE THREAD

**Issue by carsonreinke** [vcr/vcr#590]
Disabling WebMock (`WebMock.disable!()`) before configuring VCR to be hooked into it, will disable the VCR entirely.  Simply moving the `WebMock.disable!()` below the VCR configuration fixed the problem.

Not sure if anything can be fixed, but hope it helps others.

**Comment by carsonreinke** [comment]
**Nope**, totally wrong about this.  Other problems with WebMock 2+, but no this.

**Comment by mcfiredrill** [comment]
Feel free to open a new issue if you are having other problems.
