### ISSUE TITLE
Pause Recording

### ISSUE THREAD

**Issue by sirwolfgang** [vcr/vcr#592]
I have run into this need a few times. Before my wait period was a minute, so I would just manually edit the recording. This time its about a 30 min wait, so I would like to have something a little easier. Maybe there is a way to do this, and I have missed it?

Basically I have a very state and request dependent API setup, that requires me to request a resource. Wait on the resource to be ready, then download the resource. What I would ideally like to do is something a but like this:

``` ruby
before(:each) do
  request_resource

  if VCR.current_cassette.recording?
    pause_vcr
    loop while check_resource != ready
    resume_vcr
  end

  check_resource
end
```

Which should leave my VCR call log to be just the first and last request.

**Comment by krainboltgreene** [comment]
Use the block style and do the stuff you don't want to record between two blocks.

```
vcr do
  thing to record
end
thing to not record
vcr do
  thing to record
end
```
