### ISSUE TITLE
Missing documentation pages for recent versions

### ISSUE THREAD

**Issue by dcarral** [vcr/vcr#594]
After updating from v3.0.1 to v3.0.3 some tests started to fail (another topic). 

Terminal output shows (reduced):

> 
> * If you're surprised VCR is raising this error
> and want insight about how VCR attempted to handle the request,
> you can use the debug_logger configuration option to log more details [1].
> 
> [1] https://www.relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/debug-logging

Trying to reach the abovementioned URL ends up with:

![something_went_wrong](https://cloud.githubusercontent.com/assets/1498567/16340460/8cb048da-3a28-11e6-92e2-8c0147102e96.png)

When accessing this docs for another version (i.e.: [v3.0.1](https://www.relishapp.com/vcr/vcr/v/3-0-1/docs/configuration/debug-logging)), the version selector (select box @ top right corner) clearly indicates which ones are available.

Would make sense to at least redirect to the latest version available (perhaps showing a warning ribbon) if the document can't be found for a specific version?

**Comment by mcfiredrill** [comment]
Ah sorry, we need to update the docs.
@krainboltgreene I believe the relish docs have separate permissions to update them...do I have access to update them?

**Comment by mcfiredrill** [comment]
I was finally able to access to relish and update the docs!
https://www.relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/debug-logging

**Comment by dcarral** [comment]
Thanks @mcfiredrill, well done! ;)
