### ISSUE TITLE
unable to record any cassettes, with webmock 2

### ISSUE THREAD

**Issue by tansaku** [vcr/vcr#595]
Hi, followed the relish docs to try and set up vcr with rspec, but can't seem to get anything recorded into cassettes.

Full app is here: https://github.com/AgileVentures/codeclimate_badges/

had a try with macros here:

https://github.com/AgileVentures/codeclimate_badges/tree/vcr_weirdness

have been back and forth checking all sorts of possibilities, but nothing we do leads to the creation of any cassettes.

Have used VCR with cucumber on many projects many times, and works great, but am stumped by this at the moment - probably missing something obvious, but any help much appreciated.

Have even gone so far as to pull relish examples into master branch:

https://github.com/AgileVentures/codeclimate_badges/blob/master/spec/vcr_example_spec.rb

with help from http://stackoverflow.com/questions/19388474/how-can-i-use-sinatra-to-simulate-a-remote-server-in-rspec-vcr

and these are all green, but still no cassettes in the directory.

Indebted to anyone who can discover our mistake

**Comment by tswayne** [comment]
Hey @tansaku, I just ran into the same problem.  It looks like VCR does not play well with webmock v2.0.0+.  To get your app working you can lock in the version of webmock below 2, and re-title this issue.

**Comment by penman** [comment]
@tansaku you need to update to VCR 3.0.3. I tried it out on your app and it seemed to work.

**Comment by mikespokefire** [comment]
FWIW I had the same issue as @tansaku and @penman's suggestion fixed it :+1:

**Comment by tansaku** [comment]
yes thanks @penman - that fixed for me!
