### ISSUE TITLE
Need facility to automatically mask secrets in generated vcr_cassettes

### ISSUE THREAD

**Issue by reubenavery** [vcr/vcr#599]
API secret keys should never be written to disk in generated output. Period.  

There needs be some mechanism for identifying for VCR what data pieces are secrets and to have them masked by some means in the generated vcr_cassettes files.

**Comment by krainboltgreene** [comment]
You can use a different persistence adapter, but frankly there are a lot of other questions to ask:

  1. If you're using VCR in tests, why are your secret keys real?
  2. If you're using VCR in your program (for HTTP caching or analysis) then disk storage isn't an issue; if someone has access to your disk they have access to your source in most cases.

**Comment by mcfiredrill** [comment]
@reubenavery 
I use the `filter_sensitive_data` to hide my AWS credentials in VCR cassettes.
Have you used this option before?
https://relishapp.com/vcr/vcr/v/3-0-1/docs/configuration/filter-sensitive-data

**Comment by reubenavery** [comment]
Thank you @mcfiredrill this is just what I was hoping for!
