### ISSUE TITLE
Per-test hooks. How to make it right?

### ISSUE THREAD

**Issue by vanburg** [vcr/vcr#600]
Hi! Today I had one interesting problem, and need help on how to solve it smart :)
Some tests require pre-setup of remote service in order to force them raise an error, for example. VCR has ``before_http_request`` and I want to use it for that. The problem I found is how to make hooks works only for specific test, and not running on others. Take a look at this pseudocode:

```ruby
describe "Braintree" do
  let(:customer_id) { 'some_id' }

  let(:hook) do
    Proc.new do
      WebMock.allow_net_connect! do
        unless Braintree::Customer.find(customer_id).success?
          Braintree::Customer.create(id: customer_id)
        end
      end
    end
  end

  around do |example|
    VCR.configure do |c|
      # We want to check customer exists only if re-recording
      c.before_http_request(:real?, &hook)
    end

    example.run

    VCR.configure do |c|
      # HOW TO REMOVE HOOK??
    end
  end

  example "customer already exists", vcr: {cassette_name: 'braintree/customer_creation_already_exists'} do
    result = Braintree::Customer.create(id: customer_id)
    expect(result).not_to be_success
  end

  example "slightly better way", vcr: {before_http_request: hook, cassette_name: 'braintree/customer_creation_already_exists', } do
    result = Braintree::Customer.create(id: customer_id)
    expect(result).not_to be_success
  end
end
```

Question:
- how to remove this concrete hook from hooks chain, not touching the others?
- Is there a better way to do it?

Thanks!

To be clear: I know there's an ability to filter by request props, but it doesn't seems the right way in this case: we use VCR to abstract HTTP interaction, not to hack it. If (hypothetically) Braintree or it's gem will change API endpoint path somehow, that will not trigger the hook, and that will fail the test. What if I test interaction with just building API, which changes few times a week?

So, this feels not right to me:
```ruby
# before_http_request filter
lambda { |r| URI(r.uri).path =~ %r{merchants/[^/]+/customers} }
```
Beside, this hook will run each example in test suite. Using that way I may have hundreds of them uselessly running, but I need only specific one.

**Comment by vanburg** [comment]
In case someone interested in solution here is one: 
https://gist.github.com/vanburg/cbe045cafca5137a0d6c297138bba862
I really do not like ``WebMock.disable!`` && ``WebMock.enable!`` but this is the only way I found, since ``VCR#turn_off!`` is not applicable there.

**Comment by wandering-tales** [comment]
> In case someone interested in solution here is one: https://gist.github.com/vanburg/cbe045cafca5137a0d6c297138bba862 I really do not like `WebMock.disable!` && `WebMock.enable!` but this is the only way I found, since `VCR#turn_off!` is not applicable there.

I have the same issue, but that gist is not available anymore. By chance, do you remember the solution?
