### ISSUE TITLE
Add test framework specific examples to the readme

### ISSUE THREAD

**Issue by lynncyrin** [vcr/vcr#604]
Similar tools in this space, like [capybara](https://github.com/jnicklas/capybara#using-capybara-with-rspec) and [webmock](https://github.com/bblimke/webmock#rspec), have test framework specific examples. VCR installation would be slightly easier with these examples

**Comment by krainboltgreene** [comment]
We actually have this: https://relishapp.com/vcr/vcr/v/3-0-3/docs/test-frameworks
