### ISSUE TITLE
configure_rspec_metadata! is missing a usage example

### ISSUE THREAD

**Issue by lynncyrin** [vcr/vcr#605]
Specifically, this:

---

Example:

```
VCR.configure do |c|
  c.configure_rspec_metadata!
end
```

**Comment by krainboltgreene** [comment]
Does this suffice? https://relishapp.com/vcr/vcr/v/3-0-3/docs/test-frameworks/usage-with-rspec-metadata

**Comment by lynnco** [comment]
@krainboltgreene it does, yea. I would just note that, as an end user, it didn't occur to me that https://relishapp.com/vcr/vcr/ is the primary documentation source

**Comment by krainboltgreene** [comment]
Yes, this is something that I've battled with as well.

**Comment by mcfiredrill** [comment]
https://relishapp.com/vcr/vcr/  is linked at the top of the github repo and in the readme...but feel free to reopen if you think we can improve. 🌞
