### ISSUE TITLE
Mention that vcr can filter data in the readme

### ISSUE THREAD

**Issue by lynncyrin** [vcr/vcr#606]
I wouldn't be able to use VCR without the ability to filter sensitive data, and I don't think I am alone in that, so I suggest adding a line to `Features` in the readme

`* Supports filtering sensitive data from the response body`

**Comment by krainboltgreene** [comment]
Lets make this a broader discussion, @mcfiredrill do you have any opinions on what we should do with the README?

**Comment by mcfiredrill** [comment]
Sounds great to me.
We get many issues opened where people are asking if this feature exists or how to use it.

I would definitely be in favor of a PR for this. 👍

**Comment by noloman** [comment]
Hi! Is this issue still opened and valid? Thanks!

**Comment by krainboltgreene** [comment]
Closed by #677
