### ISSUE TITLE
Add an "filter_all" mode with a "allowed_parameters" option

### ISSUE THREAD

**Issue by lynncyrin** [vcr/vcr#607]
In my project, the only thing I need from VCR is `response.body.string`. Everything else is either fluff (`X-Rate-Limit-Remaining`) or sensitive data (`Authorization`). VCR could do with a mode (`filter_all`) where everything is filtered out where everything but an array of `allowed_parameters` like `response.body.string` are saved.

**Comment by krainboltgreene** [comment]
Want to make a PR?

**Comment by lynnco** [comment]
@krainboltgreene Yes I do!

**Comment by lynnco** [comment]
I'm dropping this, can't find the time to work on it
