### ISSUE TITLE
VCR::Errors::UnhandledHTTPRequestError should raise over and over?

### ISSUE THREAD

**Issue by Edouard-chin** [vcr/vcr#608]
Hey guys, thanks for this wonderful gem, we are relying on it a lot for our http interactions with different web services.
I'm unable to tell if this an issue specific to VCR but I just wanted to point this out, feel free to close this issue if it's not in the scope of this project:

When a request can't be handled, VCR raises a `VCR::Errors::UnhandledHTTPRequestError`, if this exception gets rescued for any reason (let's say another gem implement a retry logic and rescue every exceptions), then VCR will let upcoming requests go through and the original exception will be silently ignored.

``` ruby
# VCR setup to playback GET https://google.fr

begin
  Restclient.get 'https://twitter.com'
rescue #VCR::Errors::UnhandledHTTPRequestError is raised, as the url doesn't match the cassette
  retry # The retry here will make a real request on `twitter.com`
end
```

These cases are very hard to debug. Rescuing every exception is obviously not the best, I'm wondering if VCR would have a way to continue throwing the exception whenever the first one is rescued.

**Comment by mcfiredrill** [comment]
Not sure what we can do about that, libraries should definitely not be swallowing exceptions like that. :( 

I would suggest patching the Gems that are doing this instead.
