### ISSUE TITLE
Is it possible to send variables to cassette yml file ?

### ISSUE THREAD

**Issue by JulienItard** [vcr/vcr#623]

**Comment by ecnalyr** [comment]
Could you please move your question to the[ mailing list](https://groups.google.com/forum/#!forum/vcr-ruby) (you're more likely to get help over there with questions)?

Also, you may want to clarify the question with a few more details (What are you trying to accomplish? / Do you mean, "is it possible to use variables within a cassette yml file?").

**Comment by krainboltgreene** [comment]
Questions are fine for issues, IMO.

**Comment by teaforthecat** [comment]
I think you could use `config.define_cassette_placeholder` https://relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/filter-sensitive-data
