### ISSUE TITLE
no such file to load -- vcr_cucumber_helpers.rb (LoadError)

### ISSUE THREAD

**Issue by anibal** [vcr/vcr#63]
Using VCR 1.9.0 with Ruby 1.8.7 I am getting a:

```
 "no such file to load -- vcr_cucumber_helpers.rb (LoadError)"
```

From the require in features/support/vcr.rb

When I inspected the path I founf the VCR was included in `$:` as expected:

```
.rvm/gems/ruby-1.8.7-p334@dashboard/gems/vcr-1.9.0/lib
```

But the cucumber helper was not included in the search path, as it should be setup in:

https://github.com/myronmarston/vcr/blob/master/features/support/env.rb#L17

**Comment by decareano** [comment]
Hi mryon, 
When I run the VCR cucumber feature I am getting an error: `cannot load such file -- lib/server (LoadError)`. Enclosing a capture for you to look at: `https://www.dropbox.com/s/ch36x6wq9vjjflh/Screenshot%202015-03-02%2018.29.19.png?dl=0` Thanks

**Comment by krainboltgreene** [comment]
This is likely because it's not realizing you mean the relative directory.
I would try `require_relative '../lib/server'`.

**Comment by decareano** [comment]
Thanks. It's running with this error: (sample code. All scenarios have same error)
@localhost_request
  Scenario: tagged scenario                                                                                     
    When a request is made to "http://localhost:7777/localhost_request_1"                                      
      Connection refused - connect(2) (Errno::ECONNREFUSED)

Thanks for the help
