### ISSUE TITLE
Cassettes no longer being picked up after switching to postgresql

### ISSUE THREAD

**Issue by mathieujobin** [vcr/vcr#638]
I have a rails app that was running on 4.0.5, I have successfully upgraded to 4.2.7 and 5.0
and I did not need to regenerate the cassettes.

I am making this super small commit only switching the mysql2 gem for `pg` and updating the `config/database.yml`

I am trying to understand why this would make VCR not pickup the cassette? That seems so unrelated.. 

usually a webmock gem update could require cassettes to be repicked up, but nothing else changed outside of mysql->pg ? 

anyone ever encounter this? or have any idea what could be causing this?

**Comment by ecnalyr** [comment]
I have no idea what's wrong, but there are current issues with Ruby 2.4.0.  

Did you happen to also switch ruby versions during this upgrade process?

**Comment by mathieujobin** [comment]
i could not find the inderlying reason. I remade the cassettes.

thanks
