### ISSUE TITLE
VCR Does Not Support Recording Broken SSL Certs

### ISSUE THREAD

**Issue by shalecraig** [vcr/vcr#651]
I tried to use VCR (with excon, if that matters) to record various types of errors so I can make sure a client library handles them correctly.

In the code before serialization, it doesn't seem like TLS issues are considered.

Here's a code snippet that fails:

```ruby
puts VCR.version
# => 3.0.3
VCR.use_cassette('attempt_1', serialize_with: :json) do
  begin
    Excon.get('https://expired.badssl.com/') # SSL cert has expired.
  rescue => e
    # log something here
  end
end
```

The JSON failure is on [this line](https://github.com/vcr/vcr/blob/master/lib/vcr/structs.rb#L494-L498), response is `nil`, and thererefore VCR fails with the following truncated snippet:
```
NoMethodError: undefined method `to_hash' for nil:NilClass
[....]/lib/vcr/structs.rb:497:in `to_hash'
```

**Comment by andrehjr** [comment]
I've tried this with a different combination of VCR/webmock/excon versions and wasn't able to reproduce this error 🤔
