### ISSUE TITLE
Override ignore hosts inside spec

### ISSUE THREAD

**Issue by arthurmmoreira** [vcr/vcr#660]
Hello.

I would like to ask if it's possible to change the "ignore_hosts" default configuration inside my spec.

In my default configuration I have:
```ruby
VCR.configure do |config|
  config.ignore_hosts 'graph.facebook.com', 'adwords.google.com', 'accounts.google.com'
end
```

And I would like to override (or remove one) inside the spec:
```ruby
VCR.configure do |config|
  config.ignore_hosts 'adwords.google.com', 'accounts.google.com'
end
```
Any tips?

**Comment by mcfiredrill** [comment]
Have you tried it?

**Comment by bwilczek** [comment]
This PR should resolve it:
https://github.com/vcr/vcr/pull/683
