### ISSUE TITLE
cleanup old ruby 1.8 hacks

### ISSUE THREAD

**Issue by mcfiredrill** [vcr/vcr#676]
If you grep the source code for "1.8." you will probably still find a few hacks and things to support Ruby 1.8. Since we don't support 1.8 anymore these can be removed.

If anyone is looking for a place to start contributing this is a great way to start.

**Comment by aimerald** [comment]
Hi!
Is it all right to delete these codes?
```
lib/vcr/util/internet_connection.rb
2:  # Ruby 1.8 provides Ping.pingecho, but it was removed in 1.9.
8:    # This is copied, verbatim, from Ruby 1.8.7's ping.rb.
```
like this↑

If that's OK, I will remove there!

**Comment by mcfiredrill** [comment]
@aimerald 
I think we still need the ping implementation, but you can probably remove the part about trying to `require 'ping'`.
