### ISSUE TITLE
Missing v4.0.0 tag on GitHub

### ISSUE THREAD

**Issue by lucasmazza** [vcr/vcr#678]
I noticed this when going through the `CHANGELOG.md` and clicking on the "Full Changelog" link at https://github.com/vcr/vcr/blob/master/CHANGELOG.md#400 that goes to the GitHub compare page.

**Comment by mcfiredrill** [comment]
Ah shoot, forgot to push the tag...

**Comment by mcfiredrill** [comment]
Added! https://github.com/vcr/vcr/releases/tag/v4.0.0
Thanks for catching that. 🙏
