### ISSUE TITLE
the Network Communication Persistence Protocol?

### ISSUE THREAD

**Issue by mcfiredrill** [vcr/vcr#682]
This is the description for the VCR organization.

https://github.com/vcr
```
The collection of libraries for the Network Communication Persistence Protocol
 https://www.ncpp.com
```

Is this a real thing? Googling doesn't bring up anything and the website has an SSL error.

**Comment by krainboltgreene** [comment]
An attempt (never followed through) to standardize the format of cassettes. The idea being that we would have an easier way to communicate with others if we moved away from this very silly naming convention.
