### ISSUE TITLE
Record and replay external requests from Capybara, Selenium, etc.

### ISSUE THREAD

**Issue by HarlemSquirrel** [vcr/vcr#685]
I have some tests where the browser makes requests to a third party API. It would be awesome to include those interactions and be able to replay them. 

It looks like [there is no way to do that with webmock](https://github.com/bblimke/webmock/issues/681).

**Comment by krainboltgreene** [comment]
Out of the realm of our control, sadly. Likely the solution is to write a driver that also creates an http proxy that is applied to the browser. That http proxy would point to a driver-driven http server which...etc.

**Comment by krainboltgreene** [comment]
Just as likely you could do what I described above an use vcr as a middle layer. For example:

  Step 1: Create an http server that proxies to vcr which passes to a mock driver (for example webmock).
  Step 2: Create a cli that sets an http proxy on your network layer. (Go checkout various subdomain tools for how they do this, like hotel.js)
  Step 3: For the duration of the test suite, turn on the proxy, tell the browser mock http server to read from your cassettes, and then viola!

**Comment by krainboltgreene** [comment]
For what it's worth, if you wanted to implement the above we'd accept that as a PR.

**Comment by HarlemSquirrel** [comment]
Thanks for the outline! I'll see what I can do when I have a free moment.

**Comment by bblimke** [comment]
@krainboltgreene would there be a separate cassette for requests made by frontend?

**Comment by JoeSSS** [comment]
@krainboltgreene can I use the same approach in case when I need requests that are firing from "outside of the test" to the server? Currently what I see is that everything that vcr is catching is requests that test framework does to the iOS simulator, everything that simulator says to the server is unrecorded. I wonder if there is something that I can do to record everything that is going from the client to server when client is kind of not connected to the test itself.
