### ISSUE TITLE
cassettes not always rerecords because of sensitive data filtering

### ISSUE THREAD

**Issue by mathieujobin** [vcr/vcr#689]
I'm using these matching options `{ :record => :new_episodes, :match_requests_on => [:method, :uri, :body] }` so that the right cassette is being pick up, since query parameters are important.

with `:match_requests_on => [:host, :path, :method] ` I am getting random results.

but in conjunction to that,  i use `c.filter_sensitive_data('__API_KEY__')  { secret }`
which in some case ends up on the query params, part of the URI

and when locally running the scenarios, it seems like the cassette with the placeholder is not matching and the same cassettes are being recorded multiple times. that eventually leaded to a cassette file to be above 100MB; github refusing the file and cucumber getting very very slow.

I hope I am wrong, but so far, it look like this is the cause. I will keep digging, but I am posting this here meanwhile

cheers

**Comment by saveriomiroddi** [comment]
Hello mathieu; in order to understand the problem - when you write:

>  i use c.filter_sensitive_data('__API_KEY__') { secret }
which in some case ends up on the query params, part of the URI

you mean that query params shouldn't be manipulated, and the replacement is unintended, or that your application passes sensitive data (`secret` content) via query params, therefore, the manipulation is expected?

**Comment by mathieujobin** [comment]
I'm not too sure what was happening. I reverted my options back to `:match_requests_on => [:host, :path, :method]` and things are working fine again...

when I was suddenly getting "duplicate" cassettes being recorded, I thought maybe this is because the current value of `secret` (being set locally to record cassettes), is different than what is in the cassette since its being filtered for sensitive data. so when matching requests using full `:uri`, those params don't match anymore, and thus triggering a new cassette to be recorded...

**Comment by mathieujobin** [comment]
i have no idea.... but I no longer have this issue
