### ISSUE TITLE
Twitter gem - VCR::Request initialized with an invalid body

### ISSUE THREAD

**Issue by jeromedalbert** [vcr/vcr#695]
I use VCR a lot, but I can't make it work with the `twitter` gem.

### Steps to reproduce

- VCR version: 4.0.0

- Files:

```ruby
# spec/rails_helper.rb
...
require 'webmock/rspec'
require 'vcr'
...
```

```ruby
# spec/support/vcr.rb
VCR.configure do |config|
  config.cassette_library_dir = 'spec/fixtures/vcr_cassettes'
  config.hook_into :webmock
  config.configure_rspec_metadata!
end
```

```ruby
# app/services/test_twitter_vcr.rb
class TestTwitterVcr

  def run
    twitter = Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['TWITTER_CONSUMER_KEY']
      config.consumer_secret = ENV['TWITTER_CONSUMER_SECRET']
      config.access_token = ENV['TWITTER_ACCESS_TOKEN']
      config.access_token_secret = ENV['TWITTER_ACCESS_TOKEN_SECRET']
    end

    twitter.search('hello world', result_type: 'recent')
  end

end
```

```ruby
# spec/services/test_twitter_vcr_spec.rb
require 'rails_helper'

describe TestTwitterVcr do

  describe '#run', vcr: { cassette_name: 'twitter/search_tweets' } do
    it do
      expect { TestTwitterVcr.new.run }.not_to raise_error
    end
  end

end
```

- When I run `rspec spec/services/test_twitter_vcr_spec.rb`, I get the following error:

```
  1) TestTwitterVcr#run should not raise Exception
     Failure/Error: expect { TestTwitterVcr.new.run }.not_to raise_error

       expected no Exception, got #<ArgumentError: VCR::Request initialized with an invalid body: #<HTTP::Request::Body:0x00007ff43a4623b0 @body=#<HTTP::FormData::Urlencoded:0x00007ff43a4b0a10 @io=#<StringIO:0x00007ff43a4aa6b0>>>.> with backtrace:
         # ./app/services/test_twitter_vcr.rb:11:in `run'
         # ./spec/services/test_twitter_vcr_spec.rb:7:in `block (4 levels) in <top (required)>'
         # ./spec/services/test_twitter_vcr_spec.rb:7:in `block (3 levels) in <top (required)>'
         # -e:1:in `<main>'
     # ./spec/services/test_twitter_vcr_spec.rb:7:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'
```

### Comments

This may be related or not, but the `twitter` gem uses the `http.rb` gem (see also #477).

**Comment by krainboltgreene** [comment]
Looks like the body wasn't read? Hmm.

**Comment by atyndall** [comment]
The same thing is happening to me with the Twitter gem and VCR

**Comment by atyndall** [comment]
I was having a similar issue with the Twitter client and http.rb, the most simple example that I ran in our project's test environment that triggered it was;
```
irb(main):069:0>  HTTP.get('http://example.com')
ArgumentError: VCR::Request initialized with an invalid body: #<HTTP::Request::Body:0x0000000a22c590 @body=nil>
```

However, after upgrading webmock, vcr and http to their latest versions, I can no longer replicate the issue.

**Comment by jeromedalbert** [comment]
I already have the latest versions, which at the time of writing are:

- vcr 4.0.0
- webmock 3.3.0
- http 3.0.0

**Comment by cben** [comment]
Was this fixed in http 3.2.1 by httprb/http#468?
On vcr 4.0.0, **webmock 3.0.1**, http 3.3.0 I'm still seeing this as *sporadic order-dependent failures* https://github.com/abonas/kubeclient/pull/321#issuecomment-396048225.
On vcr 4.0.0, latest webmock 3.4.2, http 3.3.0 it seems fixed.
(Didn't debug, no idea if test non-isolation was fault of our kubeclient code or webmock/vcr)

**Comment by ibrahima** [comment]
FWIW, I got this error with vcr (3.0.3) and webmock (2.3.1) and http.rb 4.0.0, updating to vcr (4.0.0) and webmock (3.5.1) seemed to fix the error for me, at least for the first run. I'm using `http.rb` myself directly and not specifically for Twitter. Hope this helps anyone else who runs into this.

**Comment by kurko** [comment]
Error stopped with `webmock 3.5.1`, `vcr 4.0.0` and `http 4.1.1`.

**Comment by olleolleolle** [comment]
Sounds fixed, closing.
