### ISSUE TITLE
Old docs on Relish

### ISSUE THREAD

**Issue by tobiasfeistmantl** [vcr/vcr#698]
The [Relish Docs](https://relishapp.com/vcr/vcr/docs) still just have the docs for 3.0.3.
Would be great if they get updated.

**Comment by ajsharp** [comment]
@krainboltgreene bump. Happy to help here if it's something that needs a PR.

**Comment by krainboltgreene** [comment]
There's nothing I can do about this, relish is broken.

**Comment by krainboltgreene** [comment]
A good solution would be to find some other way of hosting documentation.

**Comment by ajsharp** [comment]
@krainboltgreene ah, didn't realize that, bummer. What about converting the existing feature files to markdown? Maybe we could start there and host them here on the wiki?
