### ISSUE TITLE
Security tokens might be exposed in cassettes

### ISSUE THREAD

**Issue by zerogvt** [vcr/vcr#704]
Security tokens (secrets) get also written down in cassettes. I noticed this in an enterprise environment (using octokit to interact with company's gh). My token was written down unencrypted and it just takes a simple grep for `token` into the cassettes to reveal it.
The token is generally not needed to replay cassettes so it could either be removed at the end of the http dialogue or not get written down in the first place.

Thanks for your efforts :+1: ! VCR is *really convenient* tool.

**Comment by krainboltgreene** [comment]
There is no way for VCR to know what data in a request is secret or not.

**Comment by mcfiredrill** [comment]
Please use the filter sensitive data feature for this
https://relishapp.com/vcr/vcr/v/1-10-0/docs/configuration/filter-sensitive-data

**Comment by vfonic** [comment]
@krainboltgreene I have the same concern/issue like @zerogvt (and probably many other people, based on the simple search for "secret" https://github.com/vcr/vcr/issues?utf8=%E2%9C%93&q=secret).

I agree with you. It's impossible for VCR to know all the secrets and tokens.

However, I think it would be really helpful if there would be a mention of this in the README.

Yes, I see the link posted by @mcfiredrill. I've been using VCR for several years now and this is the first time I see that link. It's there, but not the easiest to find, yet I think it's important enough that it should be more visible.

**Comment by vfonic** [comment]
I've created a PR if you think this is worth merging: https://github.com/vcr/vcr/pull/783
