### ISSUE TITLE
Automated filename using rpsec metadata generates path/filename longer than 260 characters

### ISSUE THREAD

**Issue by akshah123** [vcr/vcr#706]
setting the VCR cassette name based on example's full description potentially produces a file path longer than 255 characters that not all operating systems support.

For example, on windows a full path cannot be longer 260 characters.  It would be great if there was a way that vcr automatically truncated filenames/path generation in such cases.

Info on windows path limit: https://msdn.microsoft.com/en-us/library/aa365247.aspx#maxpath

**Comment by krainboltgreene** [comment]
I recently ran into that at my current company! So here's our solution:

``` ruby
config.around(:each) do |example|
  VCR.use_cassette(
    [
      # This is the file path to the spec, without the leading relative an the trailing extension to avoid confusion
      *example.file_path.gsub("./", "").gsub(".rb", "").split("/"),
      # This is a chain of the `description`s and `context`s that lead to the `it`
      *example.example_group.parent_groups.map(&:description).reverse,
      # This avoids file length issues on encrypted disks
      Digest::MD5.hexdigest(example.description)
    ].map(&:parameterize).join("/"), # Example: spec/models/want_spec/want/factories/e858a9a9ea5d758685e57ffe4b84df36
    example.metadata[:vcr_options] || {},
    &example
  )
end
```

Feel free to make a PR correcting the documentation.
