### ISSUE TITLE
Support for custom cassette file path strategies when used with RSpec

### ISSUE THREAD

**Issue by vadimt** [vcr/vcr#707]
The current behavior when specs have the added metadata of `vcr: true` creates a nested directory structure based on the nested spec name producing paths like `spec/cassettes/Spec_Describe/Context/Sub_Context/It_does_something.yml`. Would be great if there were support for customizing how cassette file paths are generated if we want to colocate cassettes with the spec files, for example. Thanks.

**Comment by krainboltgreene** [comment]
You can do that already by changing the default cassette directory and writing your own around filter, like described in #706.

**Comment by vadimt** [comment]
@krainboltgreene You can. Unfortunately that doesn't play well with `configure_rspec_metadata!` which would require writing custom handlers for other vcr options as well. What are your thoughts on adding a config option to pass a custom file naming strategy here instead? https://github.com/vcr/vcr/blob/master/lib/vcr/test_frameworks/rspec.rb

**Comment by myronmarston** [comment]
It's worth noting that VCR's built-in RSpec integration isn't meant to be the end-all, be-all of how you use VCR with RSpec.  It's pretty trivial to write your own, e.g.:

``` ruby
RSpec.configure do |c|
  c.around(:example, :vcr) do |ex|
    cassette_name = build_cassette_name(ex.metadata)
    VCR.use_cassette(cassette_name, &ex)
  end
end
```

Given how easy RSpec's metadata system makes it to integrate a tool like VCR, I don't think VCR's existing RSpec integration needs to gain some existing complexity for your use case.

**Comment by krainboltgreene** [comment]
Agreed.
