### ISSUE TITLE
Matching based on multiple domains

### ISSUE THREAD

**Issue by adaam2** [vcr/vcr#708]
We use the Prismic API quite a lot, and sometimes they use `cdn.prismic.io` or just `prismic.io` as their base API domain. There are linked resources in this API, so it is often the case that URLs for other linked endpoints are returned in the payload from an API request through to Prismic. Sometimes the URLs returned use `cdn.prismic.io`, sometimes `prismic.io` is returned.

How can I equate the two domains as being the same in my VCR config. Is there a global configuration value I can set so that VCR sees these domains as the same entity?

**Comment by krainboltgreene** [comment]
Hey Adam, this is really a symptom of [mocking things you don't own](https://github.com/testdouble/contributing-tests/wiki/Don%27t-mock-what-you-don%27t-own). You should be mocking the level above the call to Prismic, which would resolve this issue. However if you absolutely still want to use VCR then I suggest using the custom equality matcher: https://relishapp.com/vcr/vcr/v/3-0-3/docs/request-matching/register-and-use-a-custom-matcher

**Comment by adaam2** [comment]
@krainboltgreene That's perfect thanks. And an interesting article too! Will take a look to see how we can modify the code to make it less coupled to the Prismic implementation.

Cheers for the help.
