### ISSUE TITLE
Documentation website out of date

### ISSUE THREAD

**Issue by joevandyk** [vcr/vcr#712]
The latest version of vcr is 4.0.0, but the latest available version at https://relishapp.com/vcr/vcr/ is 3.0.3.

**Comment by TylerRick** [comment]
Ya, what's up with that? Anyone know how to get https://relishapp.com/vcr/vcr/ updated for the current version?

**Comment by morozgrafix** [comment]
relishapp seems to be closing down https://relishapp.com/users/sign_up (I believe they are moving towards cucumber.io/pro)

**Comment by krainboltgreene** [comment]
They also have a thing called jam. Honestly, not sure what I'll do.

**Comment by tke578** [comment]
Any updates on this?

**Comment by olleolleolle** [comment]
@tke578 You may enjoy the linked documentation https://benoittgt.github.io/vcr
