### ISSUE TITLE
Filtering of phrases with special characters fails

### ISSUE THREAD

**Issue by morgoth** [vcr/vcr#717]
I got a configuration:

```ruby
VCR.configure do |c|
  c.filter_sensitive_data("<FILTERED>") { SomeService.password }
end
```

It happens that password contains "&" character, like "some&password".
It's not filtered, as written value in the cassette is `some&amp;password` and it doesn't match with the source.

Workaround for the problem was `CGI::escapeHTML(SomeService.password)`

**Comment by dmitry** [comment]
Might be good to add the following quirk to the readme or wiki.

**Comment by olleolleolle** [comment]
@dmitry Would you like to offer a documentation PR to store the quirk?
