### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by Medvezo** [vcr/vcr#741]
In the description you have indicated that you are looking for a new maintainers. There is a project called [Code Shelter](https://www.codeshelter.co/) that pairs vetted maintainers with open source projects that need a helping hand. You can add your project there and hopefully someone will offer a help.

Here is the recent discussion on Hacker News: https://news.ycombinator.com/item?id=19199647

I am not affiliated with them, just wanted to help :wave:

**Comment by krainboltgreene** [comment]
VCR isn't abandoned, just looking for more maintainers.

**Comment by Medvezo** [comment]
@krainboltgreene I wasn't implying that this project is abandoned (neither does their homepage). Quoting the first paragraph from their page:

> Code Shelter is a collective of volunteer software developers that aims to help with maintaining popular open source projects whose authors need a hand or don't have the time to maintain them any more.

 Just thought that you could find this resource helpful.
