### ISSUE TITLE
VCR matcher fails on differentiate between 2 different `body` requests and return the same result

### ISSUE THREAD

**Issue by fguillen** [vcr/vcr#742]
{{Replace with description of the problem and code or logs to help explain your problem}}
I have two very similar cassettes:

- Cassette 1: https://pastebin.com/5waN7gbK
- Cassette 2: https://pastebin.com/zrhiccUC

Then I have two different tests one for each cassette:

    def test_cassette_1
      VCR.use_cassette("druid/cassette_1") do
        # request cassette_1
      end
    end

    def test_cassette_2
      VCR.use_cassette("druid/cassette_2") do
        # request cassette_1
      end
    end

When I execute them individually all runs well, but if I execute them together (sometimes) the cassette_2 call returns the response of cassette_1.

## VCR configuration

    VCR.configure do |config|
      config.cassette_library_dir = "test/fixtures/vcr_cassettes"
      config.hook_into :webmock
      config.default_cassette_options = { :match_requests_on => [:method, :uri, :body] }
    end

I have tried with:

    :match_requests_on => [:method, :uri, :body_as_json] 
    :match_requests_on => [:method, :uri, :body, :body_as_json] 

And not luck

## More configuration

Ruby 2.5.1
Gemfile.lock https://pastebin.com/QPjKqpgC

**Comment by krainboltgreene** [comment]
Thanks for the great detail, I'll look into this!

**Comment by fguillen** [comment]
Forget about this, it was a problem in our code, not VCR fault
