### ISSUE TITLE
Upcoming release plans

### ISSUE THREAD

**Issue by CAMOBAP795** [vcr/vcr#745]
**Is your feature request related to a problem? Please describe.**

According to [rubygems.org](https://rubygems.org/gems/vcr/versions/) and [github.com/releases](https://github.com/vcr/vcr/releases) the last release was done December 04, 2017 (~1.5 years ago)

**Describe the solution you'd like**

Push a new release to rubygems.org, looks like there is enough good enhancement to do a release if it's not possible due to some reason, may I kindly ask you to create a milestone to be able track progress till next release

**Describe alternatives you've considered**

At this moment I'm using a version from GitHub, but to be honest, I don't like this approach

**Comment by CAMOBAP795** [comment]
@krainboltgreene may I kindly ask you to show some visibility?

**Comment by krainboltgreene** [comment]
@CAMOBAP795 What do you mean?

**Comment by CAMOBAP795** [comment]
@krainboltgreene oh, sorry for bother I see https://github.com/vcr/vcr/releases/tag/v5.0.0

Thanks

**Comment by krainboltgreene** [comment]
No worries, thanks for making an issue to get me to release. I appreciate your help <3.
