### ISSUE TITLE
Revise the ArgumentError message for VCR::Request initialized with a non-String body

### ISSUE THREAD

**Issue by aploshay** [vcr/vcr#748]
**Is your feature request related to a problem? Please describe.**
A VCR::Request object performs [this following initialization check](https://github.com/vcr/vcr/blob/master/lib/vcr/structs.rb#L64-L66):
```ruby
        if body && !body.is_a?(String)
          raise ArgumentError, "#{self.class} initialized with an invalid body: #{body.inspect}."
        end
```
Based on seeing the error message out of context of the `if` check, I got hung up awhile on understanding what the problem was, for these two reasons:
1. The error message doesn't convey that's a problem of the body's _class_ (and so I thought it was a problem with the body's _content_)
2. Depending on the actual body class, the `.inspect` call might cleanly render as String content, without indicating its class.

**Describe the solution you'd like**
Amending the error text to include:
1. Explicitly stating that a `String` body is required
2. Indicating the class of the received body
So, something like:
```ruby
"#{self.class} initialized with an non-String body of class #{body.class}: #{body.inspect}."
```

**Describe alternatives you've considered**
None

**Additional context**
In my case, the received body was a `Hydra::Derivatives::IoDecorator`, which was just cleanly rendering its String file content on the `body.inspect` call.

**Comment by krainboltgreene** [comment]
I would love this as a PR.
