### ISSUE TITLE
Update the Changelog

### ISSUE THREAD

**Issue by iGEL** [vcr/vcr#749]
It would be great if you could update the [Changelog](https://github.com/vcr/vcr/blob/master/CHANGELOG.md) with the latest release. Thanks :heart:

**Comment by esambo** [comment]
There isn't much detail in other places either:
- [releases/tag/v5.0.0](https://github.com/vcr/vcr/releases/tag/v5.0.0)
- Bumping to version 5.0.0 #747
- https://github.com/vcr/vcr/commit/215e0064c99f8598173493cf741971ba7eda720a

**Comment by krainboltgreene** [comment]
@iGEL @esambo @philipbjorge @jaredmoody @biow0lf @wmotti-triboo @matthewrudy @rwojnarowski @rwojnarowski @stefanahman

Alright, now that I'm back from work and it's no longer my day off I'll create a pull request to update the changelog text file with information from the git history.

I really appreciate the created issue, thumbs ups, unhappy faces, and commentary to nudge me to update the changelog for a release I created less than a day ago on my day off. Until I finish that, feel free to read https://github.com/vcr/vcr/compare/v4.0.0...v5.0.0! If anything else is too slow for y'all or something you could contribute to the project with less time than it takes to get an uber, just let me know with more of this kind of stuff and I'll handle it. I love it.
