### ISSUE TITLE
Maintainers needed?

### ISSUE THREAD

**Issue by marcandre** [vcr/vcr#754]
I'm already spread a little thin, but I might be able to help a bit.

**Comment by skatkov** [comment]
VCR has been an essential tool in my work, last couple of years I've used it in every ruby project I worked with. I'm probably a bit too busy to commit for a full time commiter, yeat, I'd love to give a hand too.

**Comment by krainboltgreene** [comment]
While appreciated, it's not that much work to maintain VCR. It does what it says on the tin and doesn't need to do anything more than that.

Our main pain points are usually:

  - LTS shift
  - http mock library shift
  - Helping people understand it's not VCR that's the problem, but their code

All of that is handled at this point thanks to contributors.

Feel free to make some PRs on anything you see lacking.

**Comment by krainboltgreene** [comment]
Oh, and neat trick: You can approve any pull request in the world if it's visible to you. So that would also be a way to contribute.
