### ISSUE TITLE
Relish docs for version 4.0 ?

### ISSUE THREAD

**Issue by georgesmartsheet** [vcr/vcr#757]
No Relish docs for 4.0.0 or any 4.x.y

https://relishapp.com/vcr/vcr/v/3-0-3/docs/record-modes

![image](https://user-images.githubusercontent.com/50428538/59124350-40bd2680-8914-11e9-8edb-f2d92b1f3822.png)

**Comment by krainboltgreene** [comment]
Did you even look at the issue list?

**Comment by georgesmartsheet** [comment]
Yes. Why do you ask?

**Comment by krainboltgreene** [comment]
https://github.com/vcr/vcr/issues/698#issuecomment-491131826
https://github.com/vcr/vcr/issues/755
https://github.com/vcr/vcr/issues/525#issuecomment-497755009

I searched for "docs" and "relish". Literally the top 3 results.
