### ISSUE TITLE
Chromedriver update breaking specs

### ISSUE THREAD

**Issue by brandoncc** [vcr/vcr#770]
My specs pass locally, but when I push to my CI, I have these failures:

```
  An HTTP request has been made that VCR does not know how to handle:
    GET https://chromedriver.storage.googleapis.com/LATEST_RELEASE_77.0.3865
```

Is there a simple way to allow requests to https://chromedriver.storage.googleapis.com to go through?

Thanks for this gem!

**Comment by brandoncc** [comment]
It turns out my issue was coming from the `webdrivers` gem trying to update `chromedriver`. I made my CI run:

```
bundle exec rake webdrivers:chromedriver:update
```

in the setup steps and that fixed it.

**Comment by olleolleolle** [comment]
Appreciate the self-close and the explanation!
