### ISSUE TITLE
Issue with implicit cassette file name on case insensitive file system

### ISSUE THREAD

**Issue by andrykonchin** [vcr/vcr#776]
**Is your feature request related to a problem? Please describe.**

We encountered an issue with case insensitive file systems (which is a default on MacOS) and cassettes file names/directories.

We don't specify VCR cassette names explicitly so VCR generates file/directory names and they are based on RSpec's `describe`/`context`/`it` names. File name depends on letters case as well. `describe`/`context`/`it` names are changing and sometimes the only difference is a case of letters, e.g. `describe 'single package item'` could be changed to `describe 'single Package Item'`. In this case there will be two cassettes - old `.../single_package_item.yml` and new one `.../single_Package_Item.yml`.

It's completely OK on Linux but on MacOS one file will override another one and if there are two such directories MacOS will just merge them.

So we noticed that if there are two cassettes and the only difference is a case of letters in file names (e.g. `single_package_item.yml` and `single_Package_Item.yml`) VCR may use one cassette on MacOS and another one on Linux. So locally on MacOS test passes well but on CI with Ubuntu it fails because old cassette is used.

**Describe the solution you'd like**

I would like to have a way either:
* to enable downcasing of generated cassettes/nested directories (based on RSpec describe/context/it names) or
* to allow to change/process generated by VCR a path to cassette and cassette name with custom proc/lambda

**Describe alternatives you've considered**

The only alternative is detecting this duplication manually or with some git-hooks/checks on CI or configuring file system to be case sensitive (at least it's possible on MacOS).

**Additional context**

**Comment by krainboltgreene** [comment]
See: https://github.com/vcr/vcr/issues/707

**Comment by krainboltgreene** [comment]
It may be worth changing the default based on filesystem.
