### ISSUE TITLE
VCR doesn't declare its dependency on multi_json

### ISSUE THREAD

**Issue by martinemde** [vcr/vcr#789]
It seems this was discussed in #408 almost 6 years ago and it has not changed. It would be nice to add a special error message if it couldn't be loaded.

Ruby 2.5.3p105
Gem 5.0.0
Rails 5.2.2.1
Rspec 3.9.0

**Comment by krainboltgreene** [comment]
Honestly, I'd love to just toss multijson. The native json parser is OK and most people use YAML anyhow.

**Comment by krainboltgreene** [comment]
@martinemde Wanna work on this?

**Comment by EduardoGHdez** [comment]
I want 🤚
