### ISSUE TITLE
The documented set of "tested with" Ruby interpreters and the set in .travis.yml are disjoint

### ISSUE THREAD

**Issue by srawlins** [vcr/vcr#798]
README.md includes:

> VCR has been tested on the following ruby interpreters:
>
> * MRI 1.9.3
> * MRI 2.0.0
> * MRI 2.1
> * MRI 2.2
> * MRI 2.3.0
> * JRuby
> * Rubinius

But `.travis.yml` only specifies the following:

```yml
rvm:
  - 2.4
  - 2.5
  - 2.6
```

I imagine the README should be updated to specify exactly the list of interpreters found in `.travis.yml`.

**Comment by olleolleolle** [comment]
An important piece of information for this section is that the version will have to be mentioned, so that people know that since 1.0, this new list is current. 

Would you like to make a PR to that effect?

**Comment by srawlins** [comment]
Happy to open a PR! Not sure what you mean by "1.0" though. I see that:

* vcr 3.0.0 was [tested via Travis](https://github.com/vcr/vcr/blob/v3.0.0/.travis.yml) against:
  * 1.9.3
  * 2.0
  * 2.1
  * 2.2
  * jruby-19mode
  * rbx-19mode
* vcr 4.0.0 was [tested via Travis](https://github.com/vcr/vcr/blob/v4.0.0/.travis.yml) against:
  * 2.2.8
  * 2.3.5
  * 2.4.2
  * jruby-19mode
  * rbx-2
* vcr 5.0.0 was [tested via Travis](https://github.com/vcr/vcr/blob/v5.0.0/.travis.yml) against:
  * 2.4
  * 2.5
  * 2.6

Are you saying that I should mention that vcr has been tested against Ruby interpreters 2.4, 2.5, and 2.6 since version _5.0.0_?

**Comment by olleolleolle** [comment]
Ouch, that was my version-dizzy, you're absolutely right: "The 5.x series is tested with:" would do fine.
