### ISSUE TITLE
Possibly confusing "MIT-Hippocratic-1.2" license "tag" in vcr.gemspec

### ISSUE THREAD

**Issue by pombredanne** [vcr/vcr#806]
The current vcr.gemspec has this license declared: `spec.license       = "MIT-Hippocratic-1.2"`
https://github.com/vcr/vcr/blob/1f70077f73d176ab577a50033b6762b7a6d70772/vcr.gemspec#L16
I am not sure how this relate to the licensing of the package as from what I can see the license is the Hippocratic 2.0 (and there are remaining MIT obligations), but `MIT-Hippocratic-1.2` --if it means anything-- does not seem to be neither current nor correct

**Comment by krainboltgreene** [comment]
Great catch, thanks!

**Comment by pombredanne** [comment]
See https://github.com/vcr/vcr/pull/810#pullrequestreview-384078022  
I think there may still be some issues with the MIT part?
