### ISSUE TITLE
GRPC call Support?

### ISSUE THREAD

**Issue by pdkproitf** [vcr/vcr#828]
I have two components:
- Gateway (written by Rails)
- ABC_service (written by Golang)
I'm using grpc to communicate between these two services. But I don't know if this gem support grpc call. If it does so how to config? 
Please have a look. Thank a lot.

**Comment by krainboltgreene** [comment]
The best way to test would be to write a test and see if VCR captures it.

**Comment by pdkproitf** [comment]
@krainboltgreene 
I did give a try but the VCR does not capture the request. 
That why I ask if is this possible?

**Comment by krainboltgreene** [comment]
So like, yes, on a very technical level. VCR doesn't actually capture requests. It uses an adapter pattern for this so that's why you pick like webmock or faraday. Those libraries actually do the capturing.

Technically if you wrote one for tcp, you'd get grpc.

**Comment by pdkproitf** [comment]
Thank you, 
let me give a try.

**Comment by ianks** [comment]
very interested in this as well

**Comment by NielsKSchjoedt** [comment]
+1

**Comment by jontebol** [comment]
+1
