### ISSUE TITLE
Allow usage of turned_off default behavior

### ISSUE THREAD

**Issue by Vin0uz** [vcr/vcr#834]
Hi 👋

It seems to be possible to have VCR turned on by default and turn it off for some blocks, using this ([source](https://github.com/vcr/vcr/blob/8833506f74232e51a9a70c3083f71b098acac4fc/lib/vcr.rb#L289))
```
VCR.turned_off do
foo
end
``` 

Unfortunately, it seems that the opposite is not possible yet, and if VCR is set as off by default, we must do 
```
VCR.turn_on!
foo
VCR.turn_off! 
````

Would be super nice to do 
```
VCR.turned_on do 
foo 
end
```
and have therefore have the possiblity of turning off VCR by default, and wrap code that have to allow it like this, instead of constantly turning it on and off (increasing the chance to forget doing one or the other..)

It seems quite possible and logic to have both available behavior, don't you think ?

**Comment by hirowatari** [comment]
I believe this can be closed now since it's been done.  Thanks for the suggestion @Vin0uz and for pointing me in the right direction.

**Comment by Vin0uz** [comment]
Thank you guys !
