### ISSUE TITLE
Sponsoring the project is not working through GitHub.

### ISSUE THREAD

**Issue by iDuuck** [vcr/vcr#842]
I felt confident, removing those example text, because this is not regarding VCR bugs, but more of a GitHub thing.

When clicking "Sponsor", I am encountering an error:

![image](https://user-images.githubusercontent.com/325241/101999120-063b0380-3cda-11eb-9980-798e7f71056d.png)

**Comment by iDuuck** [comment]
Sorry, just saw in the "FUNDING.yml" that it's not intended to work. Never mind.

**Comment by krainboltgreene** [comment]
I don't remember making that file at all, but now it works, thanks for bringing it up.

**Comment by olleolleolle** [comment]
🎉 Thanks, @iDuuck and @krainboltgreene !
