### ISSUE TITLE
VCR tests fail with longurl::expand_urls()

### ISSUE THREAD

**Issue by bretsw** [vcr/vcr#846]
In a package I'm developing, tests for a function have been failing, and I traced the issue back to the source: `longurl::expand_urls()`

As an example of functionality, running `longurl::expand_urls("http://bit.ly/2SfWO3K", seconds=10)$expanded_url)` returns `"https://www.aect.org/about_us.php"`. 

However, putting this inside a vcr test fails, and it's unclear to me why:
 
------------------------------------------------------------

test_that("longurl::expand_urls() works for vcr", {

  vcr::use_cassette("longurl_test", {
    url1 <- longurl::expand_urls("http://bit.ly/2SfWO3K", seconds=10)$expanded_url
  })

  expect_equal(url1, "https://www.aect.org/about_us.php")
})

------------------------------------------------------------

I'm using:
- R version 4.0.2 
- VCR 0.6.0
- longurl 0.3.3
- testthat 3.0.0

**Comment by olleolleolle** [comment]
@bretsw I'm just going to ask a real simple question: Are you expecting this to be an R package? (This is a Ruby package, for recording and replaying HTTP interactions.)

**Comment by maelle** [comment]
@bretsw you were looking for https://github.com/ropensci/vcr

**Comment by olleolleolle** [comment]
Fantastic, grand, we have a workaround! Say hi to the other maintainers from the Ruby variant of vcr! 👋 

Closing this, cheers! 🍰

**Comment by bretsw** [comment]
> @bretsw I'm just going to ask a real simple question: Are you expecting this to be an R package? (This is a Ruby package, for recording and replaying HTTP interactions.)
> 
> https://rdrr.io/cran/vcr/man/use_cassette.html this seems to be the other package.

Apologies for the confusion! Thanks for resolving this quickly.

**Comment by olleolleolle** [comment]
@bretsw @maelle Your community of practice and programming seems fun and amazing. Currently studing Bret's https://bretsw.github.io/job-talk-fsu/ which is inspiring and nice.

**Comment by bretsw** [comment]
@olleolleolle You're too kind! Well, happy accident to have connected this way!
