### ISSUE TITLE
Switch to Github Actions

### ISSUE THREAD

**Issue by krainboltgreene** [vcr/vcr#848]
So Travis CI is dead. Anyone wanna create the Github Actions required to test VCR?

**Comment by bradshjg** [comment]
I've been doing this with a few libraries of mine recently, but don't have much experience with Ruby testing. Here's how I see it so far:

- [ ] `.travis.yml` -> `.github/workflows/test.yml` keeping the same test matrix and being sensitive to build times (which probably involves caching deps)
- [ ] update `README.md` with the new build badge

It's not clear to me whether the main branch test failures are test flakiness or not, so I'll wait until the PR to discuss that part of things.
