### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by AlfonsoUceda** [vcr/vcr#920]
Hi folks

Will there be any release? It seems the last one was almost 2 years ago.

Thanks

**Comment by AlfonsoUceda** [comment]
cc @myronmarston @olleolleolle

**Comment by olleolleolle** [comment]
A release is blocked by e.g https://github.com/vcr/vcr/issues/918

**Comment by deivid-rodriguez** [comment]
@olleolleolle One question. Does ver 6.0.0 support Faraday 2? If not, I don't think a new release would need to block on that? If it's a regression in master then of course it makes sense to fix it.

**Comment by olleolleolle** [comment]
@deivid-rodriguez 6.0.0 does not support Faraday 2.

**Comment by deivid-rodriguez** [comment]
Thanks! In that case, my opinion is that there's no need to block a new release on adding Faraday 2 support.

**Comment by olleolleolle** [comment]
Having looked at the changes, I think I pick 6.1.0 for the next version number. None of the `[breaking]` changelog lines seemed to be _about_ much. The JSON will be pretty-formatted, that's about it. Leaving an EOL Ruby version behind does not merit more than a MINOR.
