### ISSUE TITLE
Rspec + VCR + Dynamic results

### ISSUE THREAD

**Issue by netwire88** [vcr/vcr#938]
Hi,
I just learned about VCR and it's great. Wish I found it earlier. I was able to set it up for my app, but am encountering a situation that seems common, but is failing my rspec tests.

Here's the pseudocode

```
create a MongoDB record (or ActiveRecord), which has a unique ID
call API to create an order using that record's ID
do stuff, relying on API results
```

The test works without VCR. However, with VCR, since the ID is randomly generated, and API result is also different. How should I address this? I looked into Dynamic ERB cassettes but I can't understand [the examples](https://relishapp.com/vcr/vcr/v/1-4-0/docs/cassettes/dynamic-erb-cassettes).

**Comment by nicolasiensen** [comment]
Hey, I think you are right. You should be using dynamic ERB in this case.

Have you tried using dynamic ERB? What part of it do you not understand?

**Comment by netwire88** [comment]
Thanks @nicolasiensen  Good to know.
I had trouble using ERB with nested rspecs, but ended up figuring out a workaround that doesn't use ERBs.
