### ISSUE TITLE
http connections possible despite disabled

### ISSUE THREAD

**Issue by JHK** [vcr/vcr#965]
There seems to be an issue where VCR allows HTTP connections despite `allow_http_connections_when_no_cassette` is being set to `false`:

```ruby
VCR.configure do |c|
  c.allow_http_connections_when_no_cassette = false
  c.default_cassette_options[:record] = :new_episodes
end
```

This is likely caused by the `cassette.recording?` function ([code](https://github.com/vcr/vcr/blob/master/lib/vcr/cassette.rb#L139-L146)) being called from `real_http_connections_allowed?` ([code](https://github.com/vcr/vcr/blob/8ced6c96e01737a418cd270e0382a8c2c6d85f7f/lib/vcr.rb#L351-L354)).

Ruby 3.1.3
Gem 6.1.0

**Comment by andrehjr** [comment]
Hi 🙌 

I recently hit the same thing at work.

Going through the [code/specs](https://github.com/vcr/vcr/blob/master/spec/lib/vcr_spec.rb#L133-L144) It's clear that if there is a cassette it's possible to make real connections(depending on the record mode).

So, I'd say that this is working as expected. 

```
  The `:none` record mode guarantees that no new HTTP requests will be made.

  The `:once` record mode will:
    - Replay previously recorded interactions.
    - Record new interactions if there is no cassette file.
    - Cause an error to be raised for new requests if there is a cassette file.

  The `:new_episodes` record mode will:
    - Record new interactions.
    - Replay previously recorded interactions.
```

If what you want is to disallow any new HTTP interaction, you should configure `c.default_cassette_options[:record] = :none or :once` instead. At our company, we configure :new_episodes for local development and :none for CI.

**Comment by JHK** [comment]
Hey, you are perfectly right! Thank you for this explanation!

Setting `c.default_cassette_options[:record]` was exactly what I was looking for. I also misread the `allow_http_connections_when_no_cassette` (especially the "when no cassette") variable. Though I think it might be a useful addition to have a simple switch off for http connections, I agree that this is not a bug.
