### ISSUE TITLE
Allow requests to a specific domain

### ISSUE THREAD

**Issue by dmatamoroscr** [vcr/vcr#974]
**Is your feature request related to a problem? Please describe.**
We have a service that behaves somewhat as a database, but communicates via http. We can't easily record all the calls, since the ids will differ per-test.

**Describe the solution you'd like**
We would like to allow the requests to this service to be run, while all the rest of the http requests shoud go through VCR.

**Describe alternatives you've considered**
Find a way to easily change/specify object ids used in requests to match the current test.

**Comment by danielmbrasil** [comment]
Hey @dmatamoroscr. If I understood your request correctly, I think that you could use the `ignore_hosts` configuration in VCR. Take a look at the [documentation](https://benoittgt.github.io/vcr/#/configuration/ignore_request?id=ignore-request).

Example:
```rb
VCR.configure do |config|
  config.ignore_hosts('example.com') # all requests to this domain should be ignored by VCR
end
```

**Comment by galori** [comment]
This sounds like the right answer to me. Closing.
